
// Generated by Cadence Encounter(R) RTL Compiler v10.10-s209_1

// Verification Directory fv/ALU_RCA 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g865(.A0 (A), .B0 (Cin), .CI (B), .CO (Cout), .S0
       (S));
endmodule

module full_adder_10(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_11(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_12(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_13(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_14(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  HS65_LS_NAND2AX14 g531(.A (n_1), .B (n_3), .Z (Cout));
  HS65_LSS_XOR2X6 g532(.A (n_2), .B (Cin), .Z (S));
  HS65_LS_NAND2X14 g533(.A (n_0), .B (Cin), .Z (n_3));
  HS65_LS_HA1X4 g534(.A0 (A), .B0 (B), .CO (n_1), .S0 (n_2));
  HS65_LS_OR2X9 g535(.A (A), .B (B), .Z (n_0));
endmodule

module full_adder_15(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5;
  HS65_LS_NAND2AX14 g531(.A (n_3), .B (n_5), .Z (Cout));
  HS65_LSS_XOR2X6 g532(.A (n_4), .B (n_1), .Z (S));
  HS65_LS_NAND2X14 g533(.A (n_2), .B (Cin), .Z (n_5));
  HS65_LS_HA1X4 g534(.A0 (A), .B0 (B), .CO (n_3), .S0 (n_4));
  HS65_LS_OR2X9 g535(.A (A), .B (B), .Z (n_2));
  HS65_LS_BFX9 fopt(.A (Cin), .Z (n_1));
endmodule

module full_adder_16(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  HS65_LS_NAND2AX21 g531(.A (n_1), .B (n_3), .Z (Cout));
  HS65_LSS_XOR2X6 g532(.A (n_2), .B (Cin), .Z (S));
  HS65_LS_NAND2X14 g533(.A (n_0), .B (Cin), .Z (n_3));
  HS65_LS_HA1X4 g534(.A0 (A), .B0 (B), .CO (n_1), .S0 (n_2));
  HS65_LS_OR2X9 g535(.A (A), .B (B), .Z (n_0));
endmodule

module full_adder_17(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5;
  HS65_LS_NAND2AX29 g549(.A (n_3), .B (n_5), .Z (Cout));
  HS65_LSS_XOR2X6 g550(.A (n_4), .B (n_0), .Z (S));
  HS65_LS_NAND2AX21 g551(.A (n_2), .B (Cin), .Z (n_5));
  HS65_LS_HA1X4 g552(.A0 (A), .B0 (B), .CO (n_3), .S0 (n_4));
  HS65_LS_NOR2X6 g553(.A (A), .B (B), .Z (n_2));
  HS65_LS_BFX9 fopt(.A (Cin), .Z (n_0));
endmodule

module full_adder_18(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g533(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_19(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g539(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_1(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_4, n_6, n_13;
  HS65_LSS_XOR3X2 g602(.A (B), .B (n_0), .C (Cin), .Z (S));
  HS65_LS_NAND2X14 g603(.A (n_4), .B (n_6), .Z (Cout));
  HS65_LS_NAND2X14 g604(.A (n_13), .B (Cin), .Z (n_6));
  HS65_LS_NAND2X7 g606(.A (n_0), .B (B), .Z (n_4));
  HS65_LS_BFX9 g611(.A (A), .Z (n_0));
  HS65_LS_OR2X18 g2(.A (A), .B (B), .Z (n_13));
endmodule

module full_adder_20(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_21(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_22(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_23(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_24(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g535(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_25(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g535(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_26(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g536(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_27(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g530(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_28(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g524(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_29(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g521(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_2(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS_XOR3X2 g570(.A (B), .B (A), .C (Cin), .Z (S));
  HS65_LS_PAO2X18 g576(.A (A), .B (B), .P (Cin), .Z (Cout));
endmodule

module full_adder_30(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g519(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_31(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g552(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_3(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS_XOR3X2 g564(.A (B), .B (A), .C (Cin), .Z (S));
  HS65_LS_PAO2X18 g570(.A (A), .B (B), .P (Cin), .Z (Cout));
endmodule

module full_adder_4(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS_XOR3X2 g570(.A (B), .B (A), .C (Cin), .Z (S));
  HS65_LS_PAO2X18 g2(.A (A), .B (B), .P (Cin), .Z (Cout));
endmodule

module full_adder_5(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS_XOR3X2 g539(.A (B), .B (A), .C (Cin), .Z (S));
  HS65_LS_PAO2X18 g2(.A (A), .B (B), .P (Cin), .Z (Cout));
endmodule

module full_adder_6(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  HS65_LSS_XOR3X2 g539(.A (B), .B (A), .C (Cin), .Z (S));
  HS65_LS_NAND2X29 g540(.A (n_0), .B (n_2), .Z (Cout));
  HS65_LS_NAND2AX21 g541(.A (n_1), .B (Cin), .Z (n_2));
  HS65_LS_NOR2X6 g542(.A (A), .B (B), .Z (n_1));
  HS65_LS_NAND2X7 g543(.A (A), .B (B), .Z (n_0));
endmodule

module full_adder_7(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g539(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_8(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g541(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module full_adder_9(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  HS65_LSS1_FA1X35 g531(.A0 (A), .B0 (B), .CI (Cin), .CO (Cout), .S0
       (S));
endmodule

module RCA(A, B, Cin, Op, S, Cout, V);
  input [31:0] A, B;
  input Cin, Op;
  output [31:0] S;
  output Cout, V;
  wire [31:0] A, B;
  wire Cin, Op;
  wire [31:0] S;
  wire Cout, V;
  wire [32:0] carry;
  wire n_5, n_8, n_50, n_70;
  full_adder \rc0[0].full_add (.A (A[0]), .B (B[0]), .Cin (Cin), .S
       (S[0]), .Cout (carry[1]));
  full_adder_10 \rc0[10].full_add (.A (A[10]), .B (B[10]), .Cin
       (carry[10]), .S (S[10]), .Cout (carry[11]));
  full_adder_11 \rc0[11].full_add (.A (A[11]), .B (B[11]), .Cin
       (carry[11]), .S (S[11]), .Cout (carry[12]));
  full_adder_12 \rc0[12].full_add (.A (A[12]), .B (B[12]), .Cin
       (carry[12]), .S (S[12]), .Cout (carry[13]));
  full_adder_13 \rc0[13].full_add (.A (A[13]), .B (B[13]), .Cin
       (carry[13]), .S (S[13]), .Cout (n_70));
  full_adder_14 \rc0[14].full_add (.A (A[14]), .B (B[14]), .Cin (n_70),
       .S (S[14]), .Cout (n_50));
  full_adder_15 \rc0[15].full_add (.A (A[15]), .B (B[15]), .Cin (n_50),
       .S (S[15]), .Cout (n_5));
  full_adder_16 \rc0[16].full_add (.A (A[16]), .B (B[16]), .Cin (n_5),
       .S (S[16]), .Cout (carry[17]));
  full_adder_17 \rc0[17].full_add (.A (A[17]), .B (B[17]), .Cin
       (carry[17]), .S (S[17]), .Cout (carry[18]));
  full_adder_18 \rc0[18].full_add (.A (A[18]), .B (B[18]), .Cin
       (carry[18]), .S (S[18]), .Cout (carry[19]));
  full_adder_19 \rc0[19].full_add (.A (A[19]), .B (B[19]), .Cin
       (carry[19]), .S (S[19]), .Cout (carry[20]));
  full_adder_1 \rc0[1].full_add (.A (A[1]), .B (B[1]), .Cin (carry[1]),
       .S (S[1]), .Cout (carry[2]));
  full_adder_20 \rc0[20].full_add (.A (A[20]), .B (B[20]), .Cin
       (carry[20]), .S (S[20]), .Cout (carry[21]));
  full_adder_21 \rc0[21].full_add (.A (A[21]), .B (B[21]), .Cin
       (carry[21]), .S (S[21]), .Cout (carry[22]));
  full_adder_22 \rc0[22].full_add (.A (A[22]), .B (B[22]), .Cin
       (carry[22]), .S (S[22]), .Cout (carry[23]));
  full_adder_23 \rc0[23].full_add (.A (A[23]), .B (B[23]), .Cin
       (carry[23]), .S (S[23]), .Cout (carry[24]));
  full_adder_24 \rc0[24].full_add (.A (A[24]), .B (B[24]), .Cin
       (carry[24]), .S (S[24]), .Cout (carry[25]));
  full_adder_25 \rc0[25].full_add (.A (A[25]), .B (B[25]), .Cin
       (carry[25]), .S (S[25]), .Cout (carry[26]));
  full_adder_26 \rc0[26].full_add (.A (A[26]), .B (B[26]), .Cin
       (carry[26]), .S (S[26]), .Cout (carry[27]));
  full_adder_27 \rc0[27].full_add (.A (A[27]), .B (B[27]), .Cin
       (carry[27]), .S (S[27]), .Cout (carry[28]));
  full_adder_28 \rc0[28].full_add (.A (A[28]), .B (B[28]), .Cin
       (carry[28]), .S (S[28]), .Cout (carry[29]));
  full_adder_29 \rc0[29].full_add (.A (A[29]), .B (B[29]), .Cin
       (carry[29]), .S (S[29]), .Cout (carry[30]));
  full_adder_2 \rc0[2].full_add (.A (A[2]), .B (B[2]), .Cin (carry[2]),
       .S (S[2]), .Cout (carry[3]));
  full_adder_30 \rc0[30].full_add (.A (A[30]), .B (B[30]), .Cin
       (carry[30]), .S (S[30]), .Cout (n_8));
  full_adder_31 \rc0[31].full_add (.A (A[31]), .B (B[31]), .Cin (n_8),
       .S (S[31]), .Cout (Cout));
  full_adder_3 \rc0[3].full_add (.A (A[3]), .B (B[3]), .Cin (carry[3]),
       .S (S[3]), .Cout (carry[4]));
  full_adder_4 \rc0[4].full_add (.A (A[4]), .B (B[4]), .Cin (carry[4]),
       .S (S[4]), .Cout (carry[5]));
  full_adder_5 \rc0[5].full_add (.A (A[5]), .B (B[5]), .Cin (carry[5]),
       .S (S[5]), .Cout (carry[6]));
  full_adder_6 \rc0[6].full_add (.A (A[6]), .B (B[6]), .Cin (carry[6]),
       .S (S[6]), .Cout (carry[7]));
  full_adder_7 \rc0[7].full_add (.A (A[7]), .B (B[7]), .Cin (carry[7]),
       .S (S[7]), .Cout (carry[8]));
  full_adder_8 \rc0[8].full_add (.A (A[8]), .B (B[8]), .Cin (carry[8]),
       .S (S[8]), .Cout (carry[9]));
  full_adder_9 \rc0[9].full_add (.A (A[9]), .B (B[9]), .Cin (carry[9]),
       .S (S[9]), .Cout (carry[10]));
  HS65_LS_XOR2X18 g152(.A (Cout), .B (n_8), .Z (V));
endmodule

module logic_unit(A, B, Op, Outs);
  input [31:0] A, B;
  input [1:0] Op;
  output [31:0] Outs;
  wire [31:0] A, B;
  wire [1:0] Op;
  wire [31:0] Outs;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72;
  HS65_LS_OAI13X5 g20470(.A (A[31]), .B (B[31]), .C (n_4), .D (n_67),
       .Z (Outs[31]));
  HS65_LS_OAI31X5 g20471(.A (B[30]), .B (A[30]), .C (n_4), .D (n_59),
       .Z (Outs[30]));
  HS65_LS_OAI13X5 g20472(.A (B[26]), .B (A[26]), .C (n_4), .D (n_69),
       .Z (Outs[26]));
  HS65_LS_OAI31X5 g20473(.A (B[20]), .B (A[20]), .C (n_4), .D (n_66),
       .Z (Outs[20]));
  HS65_LS_OAI31X5 g20474(.A (B[10]), .B (A[10]), .C (n_5), .D (n_70),
       .Z (Outs[10]));
  HS65_LS_OAI31X5 g20475(.A (B[9]), .B (A[9]), .C (n_4), .D (n_68), .Z
       (Outs[9]));
  HS65_LS_OAI31X5 g20476(.A (B[8]), .B (A[8]), .C (n_4), .D (n_65), .Z
       (Outs[8]));
  HS65_LS_OAI13X5 g20477(.A (B[25]), .B (A[25]), .C (n_5), .D (n_61),
       .Z (Outs[25]));
  HS65_LS_OAI31X5 g20478(.A (B[19]), .B (A[19]), .C (n_4), .D (n_63),
       .Z (Outs[19]));
  HS65_LS_OAI31X5 g20479(.A (B[7]), .B (A[7]), .C (n_5), .D (n_64), .Z
       (Outs[7]));
  HS65_LS_OAI31X5 g20480(.A (B[6]), .B (A[6]), .C (n_5), .D (n_62), .Z
       (Outs[6]));
  HS65_LS_OAI31X5 g20481(.A (B[5]), .B (A[5]), .C (n_4), .D (n_60), .Z
       (Outs[5]));
  HS65_LS_OAI31X5 g20482(.A (B[28]), .B (A[28]), .C (n_5), .D (n_55),
       .Z (Outs[28]));
  HS65_LS_OAI31X5 g20483(.A (B[18]), .B (A[18]), .C (n_4), .D (n_58),
       .Z (Outs[18]));
  HS65_LS_OAI31X5 g20484(.A (A[4]), .B (B[4]), .C (n_5), .D (n_57), .Z
       (Outs[4]));
  HS65_LS_OAI31X5 g20485(.A (B[17]), .B (A[17]), .C (n_4), .D (n_54),
       .Z (Outs[17]));
  HS65_LS_OAI31X5 g20486(.A (B[3]), .B (A[3]), .C (n_4), .D (n_56), .Z
       (Outs[3]));
  HS65_LS_OAI13X5 g20487(.A (B[24]), .B (A[24]), .C (n_5), .D (n_52),
       .Z (Outs[24]));
  HS65_LS_OAI31X5 g20488(.A (B[2]), .B (A[2]), .C (n_4), .D (n_53), .Z
       (Outs[2]));
  HS65_LS_OAI31X5 g20489(.A (B[1]), .B (A[1]), .C (n_5), .D (n_51), .Z
       (Outs[1]));
  HS65_LS_OAI31X5 g20490(.A (B[16]), .B (A[16]), .C (n_5), .D (n_50),
       .Z (Outs[16]));
  HS65_LS_OAI31X5 g20491(.A (B[0]), .B (A[0]), .C (n_5), .D (n_49), .Z
       (Outs[0]));
  HS65_LS_OAI31X5 g20492(.A (B[29]), .B (A[29]), .C (n_5), .D (n_72),
       .Z (Outs[29]));
  HS65_LS_OAI31X5 g20493(.A (B[27]), .B (A[27]), .C (n_5), .D (n_44),
       .Z (Outs[27]));
  HS65_LS_OAI31X5 g20494(.A (B[23]), .B (A[23]), .C (n_4), .D (n_47),
       .Z (Outs[23]));
  HS65_LS_OAI31X5 g20495(.A (B[15]), .B (A[15]), .C (n_4), .D (n_48),
       .Z (Outs[15]));
  HS65_LS_OAI31X5 g20496(.A (B[14]), .B (A[14]), .C (n_5), .D (n_46),
       .Z (Outs[14]));
  HS65_LS_OAI31X5 g20497(.A (B[13]), .B (A[13]), .C (n_4), .D (n_45),
       .Z (Outs[13]));
  HS65_LS_OAI31X5 g20498(.A (B[22]), .B (A[22]), .C (n_5), .D (n_43),
       .Z (Outs[22]));
  HS65_LS_OAI31X5 g20499(.A (B[12]), .B (A[12]), .C (n_5), .D (n_42),
       .Z (Outs[12]));
  HS65_LS_OAI31X5 g20500(.A (B[21]), .B (A[21]), .C (n_5), .D (n_71),
       .Z (Outs[21]));
  HS65_LS_OAI31X5 g20501(.A (B[11]), .B (A[11]), .C (n_4), .D (n_41),
       .Z (Outs[11]));
  HS65_LS_AOI32X5 g20502(.A (n_6), .B (B[29]), .C (A[29]), .D (n_36),
       .E (n_1), .Z (n_72));
  HS65_LS_AOI32X5 g20503(.A (n_7), .B (B[21]), .C (A[21]), .D (n_39),
       .E (n_8), .Z (n_71));
  HS65_LS_AOI32X5 g20504(.A (n_7), .B (B[10]), .C (A[10]), .D (n_38),
       .E (n_1), .Z (n_70));
  HS65_LS_AOI32X5 g20505(.A (n_6), .B (B[26]), .C (A[26]), .D (n_33),
       .E (n_2), .Z (n_69));
  HS65_LS_AOI32X5 g20506(.A (n_7), .B (B[9]), .C (A[9]), .D (n_37), .E
       (n_2), .Z (n_68));
  HS65_LS_AOI32X5 g20507(.A (n_6), .B (A[31]), .C (B[31]), .D (n_21),
       .E (n_2), .Z (n_67));
  HS65_LS_AOI32X5 g20508(.A (n_7), .B (B[20]), .C (A[20]), .D (n_34),
       .E (n_8), .Z (n_66));
  HS65_LS_AOI32X5 g20509(.A (n_6), .B (B[8]), .C (A[8]), .D (n_35), .E
       (n_2), .Z (n_65));
  HS65_LS_AOI32X5 g20510(.A (n_7), .B (B[7]), .C (A[7]), .D (n_32), .E
       (n_2), .Z (n_64));
  HS65_LS_AOI32X5 g20511(.A (n_6), .B (B[19]), .C (A[19]), .D (n_31),
       .E (n_8), .Z (n_63));
  HS65_LS_AOI32X5 g20512(.A (n_7), .B (B[6]), .C (A[6]), .D (n_30), .E
       (n_1), .Z (n_62));
  HS65_LS_AOI32X5 g20513(.A (n_6), .B (B[25]), .C (A[25]), .D (n_28),
       .E (n_1), .Z (n_61));
  HS65_LS_AOI32X5 g20514(.A (n_7), .B (B[5]), .C (A[5]), .D (n_29), .E
       (n_2), .Z (n_60));
  HS65_LS_AOI32X5 g20515(.A (n_6), .B (B[30]), .C (A[30]), .D (n_17),
       .E (n_1), .Z (n_59));
  HS65_LS_AOI32X5 g20516(.A (n_7), .B (B[18]), .C (A[18]), .D (n_27),
       .E (n_8), .Z (n_58));
  HS65_LS_AOI32X5 g20517(.A (n_6), .B (A[4]), .C (B[4]), .D (n_23), .E
       (n_2), .Z (n_57));
  HS65_LS_AOI32X5 g20518(.A (n_6), .B (B[3]), .C (A[3]), .D (n_26), .E
       (n_1), .Z (n_56));
  HS65_LS_AOI32X5 g20519(.A (n_6), .B (B[28]), .C (A[28]), .D (n_18),
       .E (n_2), .Z (n_55));
  HS65_LS_AOI32X5 g20520(.A (n_7), .B (B[17]), .C (A[17]), .D (n_25),
       .E (n_8), .Z (n_54));
  HS65_LS_AOI32X5 g20521(.A (B[2]), .B (n_6), .C (A[2]), .D (n_24), .E
       (n_1), .Z (n_53));
  HS65_LS_AOI32X5 g20522(.A (n_7), .B (B[24]), .C (A[24]), .D (n_19),
       .E (n_2), .Z (n_52));
  HS65_LS_AOI32X5 g20523(.A (B[1]), .B (n_6), .C (A[1]), .D (n_22), .E
       (n_1), .Z (n_51));
  HS65_LS_AOI32X5 g20524(.A (n_7), .B (B[16]), .C (A[16]), .D (n_20),
       .E (n_1), .Z (n_50));
  HS65_LS_AOI32X5 g20525(.A (B[0]), .B (A[0]), .C (n_7), .D (n_40), .E
       (n_8), .Z (n_49));
  HS65_LS_AOI32X5 g20526(.A (n_7), .B (B[15]), .C (A[15]), .D (n_16),
       .E (n_2), .Z (n_48));
  HS65_LS_AOI32X5 g20527(.A (n_6), .B (B[23]), .C (A[23]), .D (n_15),
       .E (n_1), .Z (n_47));
  HS65_LS_AOI32X5 g20528(.A (n_7), .B (B[14]), .C (A[14]), .D (n_14),
       .E (n_8), .Z (n_46));
  HS65_LS_AOI32X5 g20529(.A (n_6), .B (B[13]), .C (A[13]), .D (n_13),
       .E (n_2), .Z (n_45));
  HS65_LS_AOI32X5 g20530(.A (n_7), .B (B[27]), .C (A[27]), .D (n_12),
       .E (n_2), .Z (n_44));
  HS65_LS_AOI32X5 g20531(.A (n_7), .B (B[22]), .C (A[22]), .D (n_10),
       .E (n_8), .Z (n_43));
  HS65_LS_AOI32X5 g20532(.A (n_6), .B (B[12]), .C (A[12]), .D (n_11),
       .E (n_1), .Z (n_42));
  HS65_LS_AOI32X5 g20533(.A (n_6), .B (B[11]), .C (A[11]), .D (n_9), .E
       (n_1), .Z (n_41));
  HS65_LSS_XOR2X6 g20534(.A (B[0]), .B (A[0]), .Z (n_40));
  HS65_LSS_XOR2X6 g20535(.A (B[21]), .B (A[21]), .Z (n_39));
  HS65_LSS_XOR2X6 g20536(.A (B[10]), .B (A[10]), .Z (n_38));
  HS65_LSS_XOR2X6 g20537(.A (B[9]), .B (A[9]), .Z (n_37));
  HS65_LSS_XOR2X6 g20538(.A (B[29]), .B (A[29]), .Z (n_36));
  HS65_LSS_XOR2X6 g20539(.A (B[8]), .B (A[8]), .Z (n_35));
  HS65_LSS_XOR2X6 g20540(.A (B[20]), .B (A[20]), .Z (n_34));
  HS65_LSS_XOR2X6 g20541(.A (B[26]), .B (A[26]), .Z (n_33));
  HS65_LSS_XOR2X6 g20542(.A (B[7]), .B (A[7]), .Z (n_32));
  HS65_LSS_XOR2X6 g20543(.A (B[19]), .B (A[19]), .Z (n_31));
  HS65_LSS_XOR2X6 g20544(.A (B[6]), .B (A[6]), .Z (n_30));
  HS65_LSS_XOR2X6 g20545(.A (B[5]), .B (A[5]), .Z (n_29));
  HS65_LSS_XOR2X6 g20546(.A (B[25]), .B (A[25]), .Z (n_28));
  HS65_LSS_XOR2X6 g20547(.A (B[18]), .B (A[18]), .Z (n_27));
  HS65_LSS_XOR2X6 g20548(.A (B[3]), .B (A[3]), .Z (n_26));
  HS65_LSS_XOR2X6 g20549(.A (B[17]), .B (A[17]), .Z (n_25));
  HS65_LSS_XOR2X6 g20550(.A (B[2]), .B (A[2]), .Z (n_24));
  HS65_LSS_XOR2X6 g20551(.A (A[4]), .B (B[4]), .Z (n_23));
  HS65_LSS_XOR2X6 g20552(.A (B[1]), .B (A[1]), .Z (n_22));
  HS65_LSS_XOR2X3 g20553(.A (B[31]), .B (A[31]), .Z (n_21));
  HS65_LSS_XOR2X6 g20554(.A (B[16]), .B (A[16]), .Z (n_20));
  HS65_LSS_XOR2X6 g20555(.A (B[24]), .B (A[24]), .Z (n_19));
  HS65_LSS_XOR2X6 g20556(.A (B[28]), .B (A[28]), .Z (n_18));
  HS65_LSS_XOR2X6 g20557(.A (A[30]), .B (B[30]), .Z (n_17));
  HS65_LSS_XOR2X6 g20558(.A (B[15]), .B (A[15]), .Z (n_16));
  HS65_LSS_XOR2X6 g20559(.A (B[23]), .B (A[23]), .Z (n_15));
  HS65_LSS_XOR2X6 g20560(.A (B[14]), .B (A[14]), .Z (n_14));
  HS65_LSS_XOR2X6 g20561(.A (B[13]), .B (A[13]), .Z (n_13));
  HS65_LSS_XOR2X6 g20562(.A (B[27]), .B (A[27]), .Z (n_12));
  HS65_LSS_XOR2X6 g20563(.A (B[12]), .B (A[12]), .Z (n_11));
  HS65_LSS_XOR2X6 g20564(.A (B[22]), .B (A[22]), .Z (n_10));
  HS65_LSS_XOR2X6 g20565(.A (B[11]), .B (A[11]), .Z (n_9));
  HS65_LS_OR2X9 g20566(.A (n_7), .B (Op[0]), .Z (n_5));
  HS65_LS_IVX9 g20567(.A (Op[1]), .Z (n_7));
  HS65_LS_BFX9 g20568(.A (Op[0]), .Z (n_8));
  HS65_LS_IVX9 drc20575(.A (Op[1]), .Z (n_6));
  HS65_LS_IVX9 drc20582(.A (n_3), .Z (n_4));
  HS65_LS_IVX9 drc20583(.A (n_5), .Z (n_3));
  HS65_LS_IVX9 drc20588(.A (n_0), .Z (n_2));
  HS65_LS_IVX9 drc20589(.A (n_0), .Z (n_1));
  HS65_LS_IVX9 drc20590(.A (Op[0]), .Z (n_0));
endmodule

module shift_left_vhdl_unsigned(A, SH, Z);
  input [31:0] A;
  input [4:0] SH;
  output [31:0] Z;
  wire [31:0] A;
  wire [4:0] SH;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_85, n_86, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_96, n_97, n_98, n_99;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_113, n_119;
  wire n_120, n_121, n_122, n_127, n_128, n_129, n_130, n_139;
  wire n_140, n_141, n_142;
  HS65_LS_OAI21X3 g1527(.A (n_80), .B (n_46), .C (n_141), .Z (Z[31]));
  HS65_LS_OAI21X3 g1528(.A (n_81), .B (n_46), .C (n_142), .Z (Z[30]));
  HS65_LS_OAI21X3 g1529(.A (n_58), .B (n_47), .C (n_140), .Z (Z[29]));
  HS65_LS_OAI21X3 g1530(.A (n_53), .B (n_47), .C (n_139), .Z (Z[28]));
  HS65_LS_OA222X4 g1531(.A (n_6), .B (n_120), .C (n_13), .D (n_95), .E
       (n_47), .F (n_86), .Z (n_142));
  HS65_LS_OA222X4 g1532(.A (n_6), .B (n_121), .C (n_13), .D (n_94), .E
       (n_47), .F (n_85), .Z (n_141));
  HS65_LS_OA222X4 g1533(.A (n_6), .B (n_119), .C (n_13), .D (n_90), .E
       (n_46), .F (n_85), .Z (n_140));
  HS65_LS_OA222X4 g1534(.A (n_6), .B (n_122), .C (n_13), .D (n_98), .E
       (n_46), .F (n_86), .Z (n_139));
  HS65_LS_OAI21X3 g1535(.A (n_58), .B (n_46), .C (n_130), .Z (Z[27]));
  HS65_LS_OAI21X3 g1536(.A (n_53), .B (n_46), .C (n_129), .Z (Z[26]));
  HS65_LS_OAI21X3 g1537(.A (n_74), .B (n_46), .C (n_128), .Z (Z[25]));
  HS65_LS_OAI21X3 g1538(.A (n_71), .B (n_46), .C (n_127), .Z (Z[24]));
  HS65_LS_OAI22X6 g1539(.A (SH[3]), .B (n_121), .C (n_14), .D (n_94),
       .Z (Z[23]));
  HS65_LS_OAI22X6 g1540(.A (SH[3]), .B (n_120), .C (n_14), .D (n_95),
       .Z (Z[22]));
  HS65_LS_OAI22X6 g1541(.A (SH[3]), .B (n_119), .C (n_14), .D (n_90),
       .Z (Z[21]));
  HS65_LS_OAI22X6 g1542(.A (SH[3]), .B (n_122), .C (n_14), .D (n_98),
       .Z (Z[20]));
  HS65_LS_OA222X4 g1543(.A (n_6), .B (n_104), .C (n_13), .D (n_97), .E
       (n_47), .F (n_74), .Z (n_130));
  HS65_LS_OA222X4 g1544(.A (n_6), .B (n_103), .C (n_13), .D (n_96), .E
       (n_47), .F (n_71), .Z (n_129));
  HS65_LS_OA222X4 g1545(.A (n_6), .B (n_102), .C (n_13), .D (n_93), .E
       (n_47), .F (n_61), .Z (n_128));
  HS65_LS_OA222X4 g1546(.A (n_6), .B (n_105), .C (n_13), .D (n_92), .E
       (n_47), .F (n_77), .Z (n_127));
  HS65_LS_OAI22X6 g1547(.A (SH[3]), .B (n_104), .C (n_14), .D (n_97),
       .Z (Z[19]));
  HS65_LS_OAI22X6 g1548(.A (SH[3]), .B (n_103), .C (n_14), .D (n_96),
       .Z (Z[18]));
  HS65_LS_OAI22X6 g1549(.A (SH[3]), .B (n_102), .C (n_14), .D (n_93),
       .Z (Z[17]));
  HS65_LS_OAI22X6 g1550(.A (SH[3]), .B (n_105), .C (n_14), .D (n_92),
       .Z (Z[16]));
  HS65_LS_AOI12X2 g1551(.A (n_15), .B (n_62), .C (n_113), .Z (n_122));
  HS65_LS_OA222X4 g1552(.A (n_5), .B (n_91), .C (n_12), .D (n_64), .E
       (n_16), .F (n_61), .Z (n_121));
  HS65_LS_OA222X4 g1553(.A (n_5), .B (n_89), .C (n_12), .D (n_63), .E
       (n_16), .F (n_77), .Z (n_120));
  HS65_LS_OA222X4 g1554(.A (n_5), .B (n_100), .C (n_12), .D (n_54), .E
       (n_16), .F (n_64), .Z (n_119));
  HS65_LS_OAI22X6 g1555(.A (n_17), .B (n_98), .C (n_14), .D (n_101), .Z
       (Z[12]));
  HS65_LS_OAI22X6 g1556(.A (n_17), .B (n_94), .C (n_14), .D (n_91), .Z
       (Z[15]));
  HS65_LS_OAI22X6 g1557(.A (n_17), .B (n_97), .C (n_14), .D (n_79), .Z
       (Z[11]));
  HS65_LS_OAI22X6 g1558(.A (n_17), .B (n_92), .C (n_6), .D (n_49), .Z
       (Z[8]));
  HS65_LS_OAI22X6 g1559(.A (n_17), .B (n_96), .C (n_14), .D (n_78), .Z
       (Z[10]));
  HS65_LS_OAI22X6 g1560(.A (n_5), .B (n_101), .C (n_12), .D (n_75), .Z
       (n_113));
  HS65_LS_OAI22X6 g1561(.A (n_17), .B (n_95), .C (n_14), .D (n_89), .Z
       (Z[14]));
  HS65_LS_OAI22X6 g1562(.A (n_17), .B (n_90), .C (n_14), .D (n_100), .Z
       (Z[13]));
  HS65_LS_OAI22X6 g1563(.A (n_17), .B (n_93), .C (n_50), .D (n_14), .Z
       (Z[9]));
  HS65_LS_NOR2X6 g1564(.A (n_17), .B (n_91), .Z (Z[7]));
  HS65_LS_NOR2X6 g1565(.A (n_17), .B (n_101), .Z (Z[4]));
  HS65_LS_NOR2X6 g1566(.A (n_17), .B (n_100), .Z (Z[5]));
  HS65_LS_NOR2X6 g1567(.A (n_17), .B (n_89), .Z (Z[6]));
  HS65_LS_AOI12X2 g1568(.A (n_15), .B (n_67), .C (n_99), .Z (n_105));
  HS65_LS_OA222X4 g1569(.A (n_5), .B (n_79), .C (n_12), .D (n_72), .E
       (n_16), .F (n_54), .Z (n_104));
  HS65_LS_OA222X4 g1570(.A (n_12), .B (n_68), .C (n_5), .D (n_78), .E
       (n_16), .F (n_75), .Z (n_103));
  HS65_LS_OA222X4 g1571(.A (n_12), .B (n_56), .C (n_5), .D (n_50), .E
       (n_16), .F (n_72), .Z (n_102));
  HS65_LS_OA22X9 g1572(.A (SH[1]), .B (n_82), .C (n_9), .D (n_25), .Z
       (n_101));
  HS65_LS_OA22X9 g1573(.A (SH[1]), .B (n_59), .C (n_9), .D (n_20), .Z
       (n_100));
  HS65_LS_OAI32X5 g1574(.A (SH[1]), .B (n_5), .C (n_48), .D (n_12), .E
       (n_66), .Z (n_99));
  HS65_LS_AOI22X6 g1575(.A (n_7), .B (n_69), .C (SH[1]), .D (n_76), .Z
       (n_98));
  HS65_LS_AOI22X6 g1576(.A (n_7), .B (n_57), .C (SH[1]), .D (n_73), .Z
       (n_97));
  HS65_LS_AOI22X6 g1577(.A (n_7), .B (n_76), .C (SH[1]), .D (n_70), .Z
       (n_96));
  HS65_LS_MUX21I1X6 g1578(.D0 (n_69), .D1 (n_66), .S0 (n_7), .Z (n_95));
  HS65_LS_MUX21I1X6 g1579(.D0 (n_65), .D1 (n_56), .S0 (n_7), .Z (n_94));
  HS65_LS_AOI22X6 g1580(.A (n_7), .B (n_73), .C (SH[1]), .D (n_55), .Z
       (n_93));
  HS65_LS_AOI22X6 g1581(.A (n_7), .B (n_70), .C (SH[1]), .D (n_60), .Z
       (n_92));
  HS65_LS_MUX21I1X6 g1582(.D0 (n_55), .D1 (n_59), .S0 (SH[1]), .Z
       (n_91));
  HS65_LS_AOI22X6 g1583(.A (n_7), .B (n_65), .C (SH[1]), .D (n_57), .Z
       (n_90));
  HS65_LS_MUX21I1X6 g1584(.D0 (n_60), .D1 (n_82), .S0 (SH[1]), .Z
       (n_89));
  HS65_LS_NOR2X6 g1585(.A (n_17), .B (n_79), .Z (Z[3]));
  HS65_LS_NOR2X6 g1586(.A (n_17), .B (n_78), .Z (Z[2]));
  HS65_LS_AOI212X4 g1587(.A (n_10), .B (A[28]), .C (n_8), .D (A[27]),
       .E (n_51), .Z (n_86));
  HS65_LS_AOI212X4 g1588(.A (n_10), .B (A[29]), .C (n_8), .D (A[28]),
       .E (n_52), .Z (n_85));
  HS65_LS_NOR2X6 g1589(.A (n_50), .B (n_17), .Z (Z[1]));
  HS65_LS_NOR2X6 g1590(.A (SH[3]), .B (n_49), .Z (Z[0]));
  HS65_LS_AOI32X5 g1591(.A (A[0]), .B (n_2), .C (SH[2]), .D (n_1), .E
       (n_38), .Z (n_82));
  HS65_LS_AOI222X2 g1592(.A (SH[2]), .B (n_34), .C (n_10), .D (A[30]),
       .E (n_8), .F (A[29]), .Z (n_81));
  HS65_LS_AOI222X2 g1593(.A (SH[2]), .B (n_27), .C (n_10), .D (A[31]),
       .E (n_8), .F (A[30]), .Z (n_80));
  HS65_LS_OA22X9 g1594(.A (n_11), .B (n_20), .C (n_24), .D (n_9), .Z
       (n_79));
  HS65_LS_OA22X9 g1595(.A (n_11), .B (n_25), .C (n_7), .D (n_48), .Z
       (n_78));
  HS65_LS_MUX21X4 g1596(.D0 (n_30), .D1 (n_40), .S0 (n_1), .Z (n_77));
  HS65_LS_OAI22X6 g1597(.A (SH[2]), .B (n_43), .C (n_1), .D (n_29), .Z
       (n_76));
  HS65_LS_MUX21X4 g1598(.D0 (n_30), .D1 (n_33), .S0 (SH[2]), .Z (n_75));
  HS65_LS_MUX21X4 g1599(.D0 (n_37), .D1 (n_39), .S0 (n_0), .Z (n_74));
  HS65_LS_OAI22X6 g1600(.A (SH[2]), .B (n_28), .C (n_0), .D (n_22), .Z
       (n_73));
  HS65_LS_MUX21X4 g1601(.D0 (n_19), .D1 (n_31), .S0 (n_0), .Z (n_72));
  HS65_LS_MUX21X4 g1602(.D0 (n_35), .D1 (n_44), .S0 (n_1), .Z (n_71));
  HS65_LS_MUX21I1X6 g1603(.D0 (n_23), .D1 (n_38), .S0 (SH[2]), .Z
       (n_70));
  HS65_LS_OAI22X6 g1604(.A (SH[2]), .B (n_45), .C (n_0), .D (n_23), .Z
       (n_69));
  HS65_LS_IVX9 g1605(.A (n_67), .Z (n_68));
  HS65_LS_OAI22X6 g1606(.A (SH[2]), .B (n_41), .C (n_1), .D (n_45), .Z
       (n_67));
  HS65_LS_MUX21X4 g1607(.D0 (n_43), .D1 (n_33), .S0 (n_1), .Z (n_66));
  HS65_LS_OAI22X6 g1608(.A (SH[2]), .B (n_19), .C (n_1), .D (n_28), .Z
       (n_65));
  HS65_LS_MUX21X4 g1609(.D0 (n_31), .D1 (n_37), .S0 (n_1), .Z (n_64));
  HS65_LS_IVX9 g1610(.A (n_62), .Z (n_63));
  HS65_LS_OAI22X6 g1611(.A (SH[2]), .B (n_35), .C (n_0), .D (n_41), .Z
       (n_62));
  HS65_LS_MUX21X4 g1612(.D0 (n_42), .D1 (n_36), .S0 (n_0), .Z (n_61));
  HS65_LS_OAI22X6 g1613(.A (SH[2]), .B (n_29), .C (n_1), .D (n_25), .Z
       (n_60));
  HS65_LS_MUX21X4 g1614(.D0 (n_24), .D1 (n_22), .S0 (n_0), .Z (n_59));
  HS65_LS_MUX21I1X6 g1615(.D0 (n_27), .D1 (n_36), .S0 (SH[2]), .Z
       (n_58));
  HS65_LS_OAI22X6 g1616(.A (SH[2]), .B (n_21), .C (n_0), .D (n_26), .Z
       (n_57));
  HS65_LS_MUX21X4 g1617(.D0 (n_21), .D1 (n_32), .S0 (n_1), .Z (n_56));
  HS65_LS_OAI22X6 g1618(.A (SH[2]), .B (n_26), .C (n_1), .D (n_20), .Z
       (n_55));
  HS65_LS_MUX21X4 g1619(.D0 (n_32), .D1 (n_42), .S0 (n_0), .Z (n_54));
  HS65_LS_MUX21I1X6 g1620(.D0 (n_34), .D1 (n_40), .S0 (SH[2]), .Z
       (n_53));
  HS65_LS_NOR2X6 g1621(.A (n_0), .B (n_39), .Z (n_52));
  HS65_LS_NOR2X6 g1622(.A (n_0), .B (n_44), .Z (n_51));
  HS65_LS_OR2X9 g1623(.A (n_11), .B (n_24), .Z (n_50));
  HS65_LS_OR2X9 g1624(.A (n_16), .B (n_48), .Z (n_49));
  HS65_LS_NAND2X7 g1625(.A (A[0]), .B (n_10), .Z (n_48));
  HS65_LS_NAND2X7 g1626(.A (SH[1]), .B (n_18), .Z (n_47));
  HS65_LS_NAND2X7 g1627(.A (n_7), .B (n_18), .Z (n_46));
  HS65_LS_AOI22X6 g1628(.A (n_2), .B (A[12]), .C (n_3), .D (A[11]), .Z
       (n_45));
  HS65_LS_AOI22X6 g1629(.A (n_4), .B (A[24]), .C (n_3), .D (A[23]), .Z
       (n_44));
  HS65_LS_AOI22X6 g1630(.A (n_2), .B (A[10]), .C (n_3), .D (A[9]), .Z
       (n_43));
  HS65_LS_AOI22X6 g1631(.A (n_2), .B (A[19]), .C (n_3), .D (A[18]), .Z
       (n_42));
  HS65_LS_AOI22X6 g1632(.A (n_2), .B (A[16]), .C (SH[0]), .D (A[15]),
       .Z (n_41));
  HS65_LS_AOI22X6 g1633(.A (n_2), .B (A[22]), .C (n_3), .D (A[21]), .Z
       (n_40));
  HS65_LS_AOI22X6 g1634(.A (n_4), .B (A[25]), .C (n_3), .D (A[24]), .Z
       (n_39));
  HS65_LS_AO22X9 g1635(.A (n_2), .B (A[4]), .C (n_3), .D (A[3]), .Z
       (n_38));
  HS65_LS_AOI22X6 g1636(.A (n_4), .B (A[21]), .C (SH[0]), .D (A[20]),
       .Z (n_37));
  HS65_LS_AOI22X6 g1637(.A (n_4), .B (A[23]), .C (SH[0]), .D (A[22]),
       .Z (n_36));
  HS65_LS_AOI22X6 g1638(.A (n_4), .B (A[20]), .C (SH[0]), .D (A[19]),
       .Z (n_35));
  HS65_LS_AO22X9 g1639(.A (n_4), .B (A[26]), .C (n_3), .D (A[25]), .Z
       (n_34));
  HS65_LS_AOI22X6 g1640(.A (n_4), .B (A[14]), .C (SH[0]), .D (A[13]),
       .Z (n_33));
  HS65_LS_AOI22X6 g1641(.A (n_2), .B (A[15]), .C (n_3), .D (A[14]), .Z
       (n_32));
  HS65_LS_AOI22X6 g1642(.A (n_2), .B (A[17]), .C (n_3), .D (A[16]), .Z
       (n_31));
  HS65_LS_AOI22X6 g1643(.A (n_2), .B (A[18]), .C (SH[0]), .D (A[17]),
       .Z (n_30));
  HS65_LS_AOI22X6 g1644(.A (n_2), .B (A[6]), .C (SH[0]), .D (A[5]), .Z
       (n_29));
  HS65_LS_AOI22X6 g1645(.A (n_4), .B (A[9]), .C (SH[0]), .D (A[8]), .Z
       (n_28));
  HS65_LS_AO22X9 g1646(.A (n_4), .B (A[27]), .C (n_3), .D (A[26]), .Z
       (n_27));
  HS65_LS_AOI22X6 g1647(.A (n_2), .B (A[7]), .C (n_3), .D (A[6]), .Z
       (n_26));
  HS65_LS_AOI22X6 g1648(.A (n_4), .B (A[2]), .C (SH[0]), .D (A[1]), .Z
       (n_25));
  HS65_LS_AOI22X6 g1649(.A (n_2), .B (A[1]), .C (A[0]), .D (SH[0]), .Z
       (n_24));
  HS65_LS_AOI22X6 g1650(.A (n_4), .B (A[8]), .C (n_3), .D (A[7]), .Z
       (n_23));
  HS65_LS_AOI22X6 g1651(.A (n_2), .B (A[5]), .C (n_3), .D (A[4]), .Z
       (n_22));
  HS65_LS_AOI22X6 g1652(.A (n_2), .B (A[11]), .C (n_3), .D (A[10]), .Z
       (n_21));
  HS65_LS_AOI22X6 g1653(.A (n_4), .B (A[3]), .C (n_3), .D (A[2]), .Z
       (n_20));
  HS65_LS_AOI22X6 g1654(.A (n_2), .B (A[13]), .C (n_3), .D (A[12]), .Z
       (n_19));
  HS65_LS_IVX9 g1655(.A (n_18), .Z (n_17));
  HS65_LS_NOR2X6 g1656(.A (SH[3]), .B (SH[4]), .Z (n_18));
  HS65_LS_IVX9 g1657(.A (n_16), .Z (n_15));
  HS65_LS_NAND2X7 g1658(.A (n_7), .B (n_5), .Z (n_16));
  HS65_LS_NAND2X7 g1659(.A (SH[3]), .B (n_5), .Z (n_14));
  HS65_LS_NAND2X7 g1660(.A (n_6), .B (SH[4]), .Z (n_13));
  HS65_LS_NAND2X7 g1661(.A (SH[1]), .B (n_5), .Z (n_12));
  HS65_LS_NAND2X7 g1662(.A (n_7), .B (n_0), .Z (n_11));
  HS65_LS_NOR2X6 g1663(.A (n_3), .B (SH[2]), .Z (n_10));
  HS65_LS_NAND2X7 g1664(.A (SH[1]), .B (n_1), .Z (n_9));
  HS65_LS_NOR2X6 g1665(.A (n_4), .B (SH[2]), .Z (n_8));
  HS65_LS_IVX9 g1666(.A (SH[1]), .Z (n_7));
  HS65_LS_IVX9 g1667(.A (SH[3]), .Z (n_6));
  HS65_LS_IVX9 g1668(.A (SH[2]), .Z (n_1));
  HS65_LS_IVX9 g1669(.A (SH[4]), .Z (n_5));
  HS65_LS_IVX9 g1685(.A (n_3), .Z (n_4));
  HS65_LS_IVX9 g1686(.A (n_2), .Z (n_3));
  HS65_LS_IVX9 g1705(.A (SH[0]), .Z (n_2));
  HS65_LS_IVX9 drc1711(.A (SH[2]), .Z (n_0));
endmodule

module shift_right_vhdl_unsigned(A, SH, Z);
  input [31:0] A;
  input [4:0] SH;
  output [31:0] Z;
  wire [31:0] A;
  wire [4:0] SH;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_95, n_96, n_97, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_125;
  wire n_129, n_133, n_134, n_135, n_136, n_137, n_140;
  HS65_LS_OAI212X5 g1527(.A (n_15), .B (n_105), .C (n_6), .D (n_122),
       .E (n_115), .Z (Z[7]));
  HS65_LS_OAI212X5 g1528(.A (n_15), .B (n_103), .C (n_6), .D (n_121),
       .E (n_114), .Z (Z[6]));
  HS65_LS_OAI12X3 g1529(.A (n_136), .B (n_6), .C (n_135), .Z (Z[1]));
  HS65_LS_OAI12X3 g1530(.A (n_140), .B (n_6), .C (n_134), .Z (Z[0]));
  HS65_LS_OAI212X5 g1531(.A (n_6), .B (n_133), .C (n_15), .D (n_109),
       .E (n_111), .Z (Z[3]));
  HS65_LS_OAI212X5 g1532(.A (n_6), .B (n_137), .C (n_15), .D (n_107),
       .E (n_110), .Z (Z[2]));
  HS65_LS_OAI22X6 g1533(.A (SH[3]), .B (n_137), .C (n_17), .D (n_107),
       .Z (Z[10]));
  HS65_LS_OAI22X6 g1534(.A (SH[3]), .B (n_136), .C (n_17), .D (n_106),
       .Z (Z[9]));
  HS65_LS_OAI22X6 g1535(.A (SH[3]), .B (n_140), .C (n_17), .D (n_104),
       .Z (Z[8]));
  HS65_LS_OAI22X6 g1536(.A (SH[3]), .B (n_133), .C (n_17), .D (n_109),
       .Z (Z[11]));
  HS65_LS_OAI212X5 g1537(.A (n_6), .B (n_120), .C (n_15), .D (n_102),
       .E (n_113), .Z (Z[5]));
  HS65_LS_OAI212X5 g1538(.A (n_6), .B (n_119), .C (n_15), .D (n_101),
       .E (n_112), .Z (Z[4]));
  HS65_LS_OAI22X6 g1539(.A (SH[3]), .B (n_120), .C (n_17), .D (n_102),
       .Z (Z[13]));
  HS65_LS_OAI22X6 g1540(.A (SH[3]), .B (n_122), .C (n_17), .D (n_105),
       .Z (Z[15]));
  HS65_LS_OAI22X6 g1541(.A (SH[3]), .B (n_121), .C (n_17), .D (n_103),
       .Z (Z[14]));
  HS65_LS_OAI22X6 g1542(.A (SH[3]), .B (n_119), .C (n_17), .D (n_101),
       .Z (Z[12]));
  HS65_LS_OAI22X6 g1543(.A (n_20), .B (n_109), .C (n_17), .D (n_118),
       .Z (Z[19]));
  HS65_LS_OAI22X6 g1544(.A (n_20), .B (n_104), .C (n_17), .D (n_108),
       .Z (Z[16]));
  HS65_LS_OAI22X6 g1545(.A (n_20), .B (n_101), .C (n_17), .D (n_85), .Z
       (Z[20]));
  HS65_LS_AOI212X4 g1546(.A (n_19), .B (n_76), .C (n_18), .D (n_79), .E
       (n_129), .Z (n_140));
  HS65_LS_OAI22X6 g1547(.A (n_20), .B (n_105), .C (n_6), .D (n_58), .Z
       (Z[23]));
  HS65_LS_OAI22X6 g1548(.A (n_20), .B (n_102), .C (n_17), .D (n_84), .Z
       (Z[21]));
  HS65_LS_AOI222X2 g1549(.A (n_19), .B (n_79), .C (n_18), .D (n_61), .E
       (SH[4]), .F (n_116), .Z (n_137));
  HS65_LS_AOI222X2 g1550(.A (n_19), .B (n_77), .C (n_18), .D (n_83), .E
       (SH[4]), .F (n_100), .Z (n_136));
  HS65_LS_OA222X4 g1551(.A (n_49), .B (n_88), .C (n_51), .D (n_86), .E
       (n_15), .F (n_106), .Z (n_135));
  HS65_LS_OA222X4 g1552(.A (n_49), .B (n_91), .C (n_51), .D (n_89), .E
       (n_15), .F (n_104), .Z (n_134));
  HS65_LS_AOI222X2 g1553(.A (n_19), .B (n_83), .C (n_18), .D (n_64), .E
       (SH[4]), .F (n_117), .Z (n_133));
  HS65_LS_OAI21X3 g1554(.A (n_106), .B (n_20), .C (n_123), .Z (Z[17]));
  HS65_LS_OAI22X6 g1555(.A (n_20), .B (n_103), .C (n_17), .D (n_59), .Z
       (Z[22]));
  HS65_LS_OAI21X3 g1556(.A (n_107), .B (n_20), .C (n_125), .Z (Z[18]));
  HS65_LS_NOR2X6 g1557(.A (n_1), .B (n_108), .Z (n_129));
  HS65_LS_NOR2X6 g1558(.A (n_20), .B (n_118), .Z (Z[27]));
  HS65_LS_NOR2X6 g1559(.A (n_20), .B (n_108), .Z (Z[24]));
  HS65_LS_NOR2AX3 g1560(.A (n_116), .B (n_20), .Z (Z[26]));
  HS65_LS_NAND2X7 g1561(.A (n_16), .B (n_116), .Z (n_125));
  HS65_LS_NOR2AX3 g1562(.A (n_100), .B (n_20), .Z (Z[25]));
  HS65_LS_NAND2X7 g1563(.A (n_16), .B (n_100), .Z (n_123));
  HS65_LS_AOI212X4 g1564(.A (n_19), .B (n_68), .C (n_18), .D (n_73), .E
       (n_56), .Z (n_122));
  HS65_LS_AOI212X4 g1565(.A (n_19), .B (n_66), .C (n_18), .D (n_72), .E
       (n_95), .Z (n_121));
  HS65_LS_AOI212X4 g1566(.A (n_19), .B (n_64), .C (n_18), .D (n_68), .E
       (n_97), .Z (n_120));
  HS65_LS_AOI212X4 g1567(.A (n_19), .B (n_61), .C (n_18), .D (n_66), .E
       (n_96), .Z (n_119));
  HS65_LS_IVX9 g1568(.A (n_117), .Z (n_118));
  HS65_LS_OAI22X6 g1569(.A (SH[1]), .B (n_92), .C (n_12), .D (n_42), .Z
       (n_117));
  HS65_LS_OAI22X6 g1570(.A (SH[1]), .B (n_67), .C (n_12), .D (n_26), .Z
       (n_116));
  HS65_LS_AOI22X6 g1571(.A (n_50), .B (n_74), .C (n_52), .D (n_77), .Z
       (n_115));
  HS65_LS_AOI22X6 g1572(.A (n_50), .B (n_62), .C (n_52), .D (n_76), .Z
       (n_114));
  HS65_LS_AOI22X6 g1573(.A (n_50), .B (n_65), .C (n_52), .D (n_74), .Z
       (n_113));
  HS65_LS_AOI22X6 g1574(.A (n_50), .B (n_71), .C (n_52), .D (n_62), .Z
       (n_112));
  HS65_LS_AOI22X6 g1575(.A (n_50), .B (n_87), .C (n_52), .D (n_65), .Z
       (n_111));
  HS65_LS_AOI22X6 g1576(.A (n_50), .B (n_90), .C (n_52), .D (n_71), .Z
       (n_110));
  HS65_LS_AOI22X6 g1577(.A (n_0), .B (n_78), .C (SH[1]), .D (n_63), .Z
       (n_109));
  HS65_LS_MUX21I1X6 g1578(.D0 (n_82), .D1 (n_67), .S0 (SH[1]), .Z
       (n_108));
  HS65_LS_AOI22X6 g1579(.A (n_0), .B (n_75), .C (SH[1]), .D (n_81), .Z
       (n_107));
  HS65_LS_AOI22X6 g1580(.A (n_0), .B (n_73), .C (SH[1]), .D (n_78), .Z
       (n_106));
  HS65_LS_AOI22X6 g1581(.A (n_0), .B (n_70), .C (SH[1]), .D (n_80), .Z
       (n_105));
  HS65_LS_AOI22X6 g1582(.A (n_0), .B (n_72), .C (SH[1]), .D (n_75), .Z
       (n_104));
  HS65_LS_AOI22X6 g1583(.A (n_0), .B (n_69), .C (SH[1]), .D (n_82), .Z
       (n_103));
  HS65_LS_AOI22X6 g1584(.A (n_0), .B (n_63), .C (SH[1]), .D (n_70), .Z
       (n_102));
  HS65_LS_AOI22X6 g1585(.A (n_0), .B (n_81), .C (SH[1]), .D (n_69), .Z
       (n_101));
  HS65_LS_MUX21I1X6 g1586(.D0 (n_92), .D1 (n_80), .S0 (n_0), .Z
       (n_100));
  HS65_LS_NOR2X6 g1587(.A (n_20), .B (n_84), .Z (Z[29]));
  HS65_LS_NOR2X6 g1588(.A (n_20), .B (n_85), .Z (Z[28]));
  HS65_LS_NOR2X6 g1589(.A (n_1), .B (n_84), .Z (n_97));
  HS65_LS_NOR2X6 g1590(.A (n_1), .B (n_85), .Z (n_96));
  HS65_LS_NOR2X6 g1591(.A (n_1), .B (n_59), .Z (n_95));
  HS65_LS_NOR2X6 g1592(.A (n_20), .B (n_59), .Z (Z[30]));
  HS65_LS_NOR2X6 g1593(.A (SH[3]), .B (n_58), .Z (Z[31]));
  HS65_LS_AOI32X5 g1594(.A (n_8), .B (SH[2]), .C (A[31]), .D (n_4), .E
       (n_43), .Z (n_92));
  HS65_LS_AOI212X4 g1595(.A (A[0]), .B (n_13), .C (A[1]), .D (n_11), .E
       (n_57), .Z (n_91));
  HS65_LS_IVX7 g1596(.A (n_89), .Z (n_90));
  HS65_LS_OA12X9 g1597(.A (n_4), .B (n_34), .C (n_55), .Z (n_89));
  HS65_LS_AOI212X4 g1598(.A (A[1]), .B (n_13), .C (A[2]), .D (n_11), .E
       (n_60), .Z (n_88));
  HS65_LS_IVX7 g1599(.A (n_86), .Z (n_87));
  HS65_LS_OA12X9 g1600(.A (n_5), .B (n_37), .C (n_54), .Z (n_86));
  HS65_LS_OA22X9 g1601(.A (n_14), .B (n_26), .C (n_12), .D (n_35), .Z
       (n_85));
  HS65_LS_OA22X9 g1602(.A (n_14), .B (n_42), .C (n_0), .D (n_53), .Z
       (n_84));
  HS65_LS_OAI22X6 g1603(.A (SH[2]), .B (n_48), .C (n_2), .D (n_22), .Z
       (n_83));
  HS65_LS_OAI22X6 g1604(.A (SH[2]), .B (n_39), .C (n_4), .D (n_26), .Z
       (n_82));
  HS65_LS_OAI22X6 g1605(.A (n_3), .B (n_47), .C (n_5), .D (n_39), .Z
       (n_81));
  HS65_LS_OAI22X6 g1606(.A (n_3), .B (n_36), .C (n_5), .D (n_42), .Z
       (n_80));
  HS65_LS_OAI22X6 g1607(.A (SH[2]), .B (n_44), .C (n_2), .D (n_28), .Z
       (n_79));
  HS65_LS_OAI22X6 g1608(.A (n_3), .B (n_41), .C (n_5), .D (n_33), .Z
       (n_78));
  HS65_LS_OAI22X6 g1609(.A (n_3), .B (n_40), .C (n_5), .D (n_45), .Z
       (n_77));
  HS65_LS_OAI22X6 g1610(.A (n_3), .B (n_24), .C (n_5), .D (n_23), .Z
       (n_76));
  HS65_LS_OAI22X6 g1611(.A (SH[2]), .B (n_38), .C (n_5), .D (n_29), .Z
       (n_75));
  HS65_LS_OAI22X6 g1612(.A (n_3), .B (n_37), .C (n_2), .D (n_48), .Z
       (n_74));
  HS65_LS_OAI22X6 g1613(.A (n_3), .B (n_30), .C (n_5), .D (n_25), .Z
       (n_73));
  HS65_LS_OAI22X6 g1614(.A (SH[2]), .B (n_32), .C (n_4), .D (n_47), .Z
       (n_72));
  HS65_LS_OAI22X6 g1615(.A (n_3), .B (n_46), .C (n_2), .D (n_24), .Z
       (n_71));
  HS65_LS_MUX21I1X6 g1616(.D0 (n_33), .D1 (n_43), .S0 (n_3), .Z (n_70));
  HS65_LS_OAI22X6 g1617(.A (n_3), .B (n_29), .C (n_5), .D (n_27), .Z
       (n_69));
  HS65_LS_OAI22X6 g1618(.A (n_3), .B (n_22), .C (n_5), .D (n_41), .Z
       (n_68));
  HS65_LS_MUX21X4 g1619(.D0 (n_35), .D1 (n_27), .S0 (n_4), .Z (n_67));
  HS65_LS_OAI22X6 g1620(.A (n_3), .B (n_28), .C (n_5), .D (n_38), .Z
       (n_66));
  HS65_LS_OAI22X6 g1621(.A (n_3), .B (n_31), .C (n_2), .D (n_40), .Z
       (n_65));
  HS65_LS_OAI22X6 g1622(.A (SH[2]), .B (n_45), .C (n_5), .D (n_30), .Z
       (n_64));
  HS65_LS_OAI22X6 g1623(.A (n_3), .B (n_25), .C (n_2), .D (n_36), .Z
       (n_63));
  HS65_LS_OAI22X6 g1624(.A (n_3), .B (n_34), .C (n_2), .D (n_44), .Z
       (n_62));
  HS65_LS_OAI22X6 g1625(.A (n_3), .B (n_23), .C (n_5), .D (n_32), .Z
       (n_61));
  HS65_LS_NOR2X6 g1626(.A (n_5), .B (n_31), .Z (n_60));
  HS65_LS_OR2X9 g1627(.A (n_14), .B (n_35), .Z (n_59));
  HS65_LS_NAND2AX7 g1628(.A (n_53), .B (n_19), .Z (n_58));
  HS65_LS_NOR2X6 g1629(.A (n_5), .B (n_46), .Z (n_57));
  HS65_LS_NOR3X4 g1630(.A (SH[1]), .B (n_1), .C (n_53), .Z (n_56));
  HS65_LS_AOI22X6 g1631(.A (A[2]), .B (n_13), .C (A[3]), .D (n_11), .Z
       (n_55));
  HS65_LS_AOI22X6 g1632(.A (A[3]), .B (n_13), .C (A[4]), .D (n_11), .Z
       (n_54));
  HS65_LS_NAND2X7 g1633(.A (n_13), .B (A[31]), .Z (n_53));
  HS65_LS_IVX9 g1634(.A (n_52), .Z (n_51));
  HS65_LS_AND2X4 g1635(.A (SH[1]), .B (n_21), .Z (n_52));
  HS65_LS_IVX9 g1636(.A (n_50), .Z (n_49));
  HS65_LS_AND2X4 g1637(.A (n_0), .B (n_21), .Z (n_50));
  HS65_LS_AOI22X6 g1638(.A (n_10), .B (A[11]), .C (SH[0]), .D (A[12]),
       .Z (n_48));
  HS65_LS_AOI22X6 g1639(.A (n_8), .B (A[20]), .C (SH[0]), .D (A[21]),
       .Z (n_47));
  HS65_LS_AOI22X6 g1640(.A (n_8), .B (A[4]), .C (SH[0]), .D (A[5]), .Z
       (n_46));
  HS65_LS_AOI22X6 g1641(.A (n_8), .B (A[13]), .C (n_9), .D (A[14]), .Z
       (n_45));
  HS65_LS_AOI22X6 g1642(.A (n_10), .B (A[10]), .C (SH[0]), .D (A[11]),
       .Z (n_44));
  HS65_LS_AO22X9 g1643(.A (n_10), .B (A[27]), .C (n_9), .D (A[28]), .Z
       (n_43));
  HS65_LS_AOI22X6 g1644(.A (n_10), .B (A[29]), .C (n_9), .D (A[30]), .Z
       (n_42));
  HS65_LS_AOI22X6 g1645(.A (n_8), .B (A[19]), .C (n_9), .D (A[20]), .Z
       (n_41));
  HS65_LS_AOI22X6 g1646(.A (n_8), .B (A[9]), .C (n_9), .D (A[10]), .Z
       (n_40));
  HS65_LS_AOI22X6 g1647(.A (n_8), .B (A[24]), .C (SH[0]), .D (A[25]),
       .Z (n_39));
  HS65_LS_AOI22X6 g1648(.A (n_8), .B (A[18]), .C (SH[0]), .D (A[19]),
       .Z (n_38));
  HS65_LS_AOI22X6 g1649(.A (n_8), .B (A[7]), .C (n_9), .D (A[8]), .Z
       (n_37));
  HS65_LS_AOI22X6 g1650(.A (n_8), .B (A[25]), .C (SH[0]), .D (A[26]),
       .Z (n_36));
  HS65_LS_AOI22X6 g1651(.A (n_8), .B (A[30]), .C (SH[0]), .D (A[31]),
       .Z (n_35));
  HS65_LS_AOI22X6 g1652(.A (n_8), .B (A[6]), .C (n_9), .D (A[7]), .Z
       (n_34));
  HS65_LS_AOI22X6 g1653(.A (n_8), .B (A[23]), .C (SH[0]), .D (A[24]),
       .Z (n_33));
  HS65_LS_AOI22X6 g1654(.A (n_8), .B (A[16]), .C (SH[0]), .D (A[17]),
       .Z (n_32));
  HS65_LS_AOI22X6 g1655(.A (n_10), .B (A[5]), .C (SH[0]), .D (A[6]), .Z
       (n_31));
  HS65_LS_AOI22X6 g1656(.A (n_8), .B (A[17]), .C (n_9), .D (A[18]), .Z
       (n_30));
  HS65_LS_AOI22X6 g1657(.A (n_10), .B (A[22]), .C (SH[0]), .D (A[23]),
       .Z (n_29));
  HS65_LS_AOI22X6 g1658(.A (n_10), .B (A[14]), .C (SH[0]), .D (A[15]),
       .Z (n_28));
  HS65_LS_AOI22X6 g1659(.A (n_8), .B (A[26]), .C (SH[0]), .D (A[27]),
       .Z (n_27));
  HS65_LS_AOI22X6 g1660(.A (n_8), .B (A[28]), .C (SH[0]), .D (A[29]),
       .Z (n_26));
  HS65_LS_AOI22X6 g1661(.A (n_8), .B (A[21]), .C (n_9), .D (A[22]), .Z
       (n_25));
  HS65_LS_AOI22X6 g1662(.A (n_8), .B (A[8]), .C (SH[0]), .D (A[9]), .Z
       (n_24));
  HS65_LS_AOI22X6 g1663(.A (n_10), .B (A[12]), .C (SH[0]), .D (A[13]),
       .Z (n_23));
  HS65_LS_AOI22X6 g1664(.A (n_10), .B (A[15]), .C (n_9), .D (A[16]), .Z
       (n_22));
  HS65_LS_IVX9 g1665(.A (n_21), .Z (n_20));
  HS65_LS_NOR2X6 g1666(.A (SH[3]), .B (SH[4]), .Z (n_21));
  HS65_LS_AND2X4 g1667(.A (n_0), .B (n_1), .Z (n_19));
  HS65_LS_AND2X4 g1668(.A (SH[1]), .B (n_1), .Z (n_18));
  HS65_LS_IVX9 g1669(.A (n_17), .Z (n_16));
  HS65_LS_NAND2X7 g1670(.A (SH[3]), .B (n_1), .Z (n_17));
  HS65_LS_NAND2X7 g1671(.A (n_6), .B (SH[4]), .Z (n_15));
  HS65_LS_NAND2X7 g1672(.A (n_0), .B (n_4), .Z (n_14));
  HS65_LS_NOR2X6 g1673(.A (SH[0]), .B (SH[2]), .Z (n_13));
  HS65_LS_NAND2X7 g1674(.A (SH[1]), .B (n_4), .Z (n_12));
  HS65_LS_NOR2X6 g1675(.A (n_10), .B (SH[2]), .Z (n_11));
  HS65_LS_IVX9 g1691(.A (SH[0]), .Z (n_10));
  HS65_LS_IVX9 g1694(.A (n_10), .Z (n_9));
  HS65_LS_IVX9 g1707(.A (SH[0]), .Z (n_8));
  HS65_LS_IVX9 g1710(.A (SH[3]), .Z (n_6));
  HS65_LS_IVX7 g1722(.A (SH[2]), .Z (n_5));
  HS65_LS_IVX7 g1732(.A (SH[2]), .Z (n_4));
  HS65_LS_IVX7 g1736(.A (n_3), .Z (n_2));
  HS65_LS_BFX9 g1743(.A (SH[2]), .Z (n_3));
  HS65_LS_IVX9 g1746(.A (SH[4]), .Z (n_1));
  HS65_LS_IVX9 g1747(.A (SH[1]), .Z (n_0));
endmodule

module arith_shift_right_vhdl_unsigned(A, SH, Z);
  input [31:0] A;
  input [4:0] SH;
  output [31:0] Z;
  wire [31:0] A;
  wire [4:0] SH;
  wire [31:0] Z;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127;
  assign Z[31] = 1'b0;
  HS65_LS_OAI12X3 g2729(.A (n_127), .B (SH[4]), .C (n_16), .Z (Z[26]));
  HS65_LS_OAI12X3 g2730(.A (n_126), .B (SH[4]), .C (n_16), .Z (Z[25]));
  HS65_LS_OAI12X3 g2731(.A (n_125), .B (SH[4]), .C (n_16), .Z (Z[24]));
  HS65_LS_OAI12X3 g2732(.A (n_124), .B (SH[4]), .C (n_16), .Z (Z[23]));
  HS65_LS_OAI12X3 g2733(.A (n_122), .B (SH[4]), .C (n_16), .Z (Z[30]));
  HS65_LS_OAI12X3 g2734(.A (n_123), .B (SH[4]), .C (n_16), .Z (Z[29]));
  HS65_LS_OAI212X5 g2735(.A (n_11), .B (n_124), .C (n_13), .D (n_84),
       .E (n_104), .Z (Z[7]));
  HS65_LS_OAI212X5 g2736(.A (n_11), .B (n_113), .C (n_13), .D (n_83),
       .E (n_103), .Z (Z[6]));
  HS65_LS_OAI212X5 g2737(.A (n_11), .B (n_117), .C (n_13), .D (n_100),
       .E (n_102), .Z (Z[5]));
  HS65_LS_OAI212X5 g2738(.A (n_11), .B (n_119), .C (n_13), .D (n_98),
       .E (n_101), .Z (Z[4]));
  HS65_LS_OAI12X3 g2739(.A (n_117), .B (SH[4]), .C (n_16), .Z (Z[21]));
  HS65_LS_OAI12X3 g2740(.A (n_116), .B (SH[4]), .C (n_16), .Z (Z[18]));
  HS65_LS_OAI12X3 g2741(.A (n_115), .B (SH[4]), .C (n_16), .Z (Z[17]));
  HS65_LS_OAI12X3 g2742(.A (n_114), .B (SH[4]), .C (n_16), .Z (Z[16]));
  HS65_LS_OAI12X3 g2743(.A (n_113), .B (SH[4]), .C (n_16), .Z (Z[22]));
  HS65_LS_OAI12X3 g2744(.A (n_119), .B (SH[4]), .C (n_16), .Z (Z[20]));
  HS65_LS_OAI12X3 g2745(.A (n_118), .B (SH[4]), .C (n_16), .Z (Z[19]));
  HS65_LS_OAI12X3 g2746(.A (n_121), .B (SH[4]), .C (n_16), .Z (Z[28]));
  HS65_LS_OAI12X3 g2747(.A (n_120), .B (SH[4]), .C (n_16), .Z (Z[27]));
  HS65_LS_OAI212X5 g2748(.A (n_11), .B (n_115), .C (n_13), .D (n_93),
       .E (n_111), .Z (Z[1]));
  HS65_LS_OAI212X5 g2749(.A (n_11), .B (n_114), .C (n_13), .D (n_91),
       .E (n_112), .Z (Z[0]));
  HS65_LS_OAI222X2 g2750(.A (n_0), .B (n_95), .C (n_11), .D (n_127), .E
       (n_13), .F (n_89), .Z (Z[10]));
  HS65_LS_OAI222X2 g2751(.A (n_0), .B (n_93), .C (n_11), .D (n_126), .E
       (n_13), .F (n_87), .Z (Z[9]));
  HS65_LS_OAI222X2 g2752(.A (n_0), .B (n_91), .C (n_11), .D (n_125), .E
       (n_13), .F (n_86), .Z (Z[8]));
  HS65_LS_OAI222X2 g2753(.A (n_11), .B (n_122), .C (n_0), .D (n_83), .E
       (n_13), .F (n_82), .Z (Z[14]));
  HS65_LS_OAI222X2 g2754(.A (n_11), .B (n_123), .C (n_0), .D (n_100),
       .E (n_13), .F (n_97), .Z (Z[13]));
  HS65_LS_OAI212X5 g2755(.A (n_11), .B (n_118), .C (n_13), .D (n_96),
       .E (n_105), .Z (Z[3]));
  HS65_LS_OAI212X5 g2756(.A (n_11), .B (n_116), .C (n_13), .D (n_95),
       .E (n_106), .Z (Z[2]));
  HS65_LS_OAI222X2 g2757(.A (n_11), .B (n_121), .C (n_0), .D (n_98), .E
       (n_13), .F (n_94), .Z (Z[12]));
  HS65_LS_OAI222X2 g2758(.A (n_0), .B (n_96), .C (n_11), .D (n_120), .E
       (n_13), .F (n_90), .Z (Z[11]));
  HS65_LS_OAI212X5 g2759(.A (n_13), .B (n_85), .C (n_0), .D (n_84), .E
       (n_16), .Z (Z[15]));
  HS65_LS_OA12X9 g2760(.A (SH[3]), .B (n_99), .C (n_17), .Z (n_127));
  HS65_LS_OA12X9 g2761(.A (SH[3]), .B (n_92), .C (n_17), .Z (n_126));
  HS65_LS_OA12X9 g2762(.A (SH[3]), .B (n_88), .C (n_17), .Z (n_125));
  HS65_LS_OA12X9 g2763(.A (SH[3]), .B (n_85), .C (n_17), .Z (n_124));
  HS65_LS_OA12X9 g2764(.A (SH[3]), .B (n_109), .C (n_17), .Z (n_123));
  HS65_LS_OA12X9 g2765(.A (SH[3]), .B (n_110), .C (n_17), .Z (n_122));
  HS65_LS_OA12X9 g2766(.A (SH[3]), .B (n_108), .C (n_17), .Z (n_121));
  HS65_LS_OA12X9 g2767(.A (SH[3]), .B (n_107), .C (n_17), .Z (n_120));
  HS65_LS_MUX21X4 g2768(.D0 (n_94), .D1 (n_108), .S0 (SH[3]), .Z
       (n_119));
  HS65_LS_MUX21X4 g2769(.D0 (n_90), .D1 (n_107), .S0 (SH[3]), .Z
       (n_118));
  HS65_LS_MUX21X4 g2770(.D0 (n_97), .D1 (n_109), .S0 (SH[3]), .Z
       (n_117));
  HS65_LS_MUX21X4 g2771(.D0 (n_89), .D1 (n_99), .S0 (SH[3]), .Z
       (n_116));
  HS65_LS_MUX21X4 g2772(.D0 (n_87), .D1 (n_92), .S0 (SH[3]), .Z
       (n_115));
  HS65_LS_MUX21X4 g2773(.D0 (n_86), .D1 (n_88), .S0 (SH[3]), .Z
       (n_114));
  HS65_LS_MUX21X4 g2774(.D0 (n_82), .D1 (n_110), .S0 (SH[3]), .Z
       (n_113));
  HS65_LS_OA222X4 g2775(.A (n_37), .B (n_54), .C (n_52), .D (n_73), .E
       (n_29), .F (n_53), .Z (n_112));
  HS65_LS_OA222X4 g2776(.A (n_30), .B (n_54), .C (n_52), .D (n_69), .E
       (n_34), .F (n_53), .Z (n_111));
  HS65_LS_AOI12X2 g2777(.A (n_1), .B (n_80), .C (n_15), .Z (n_110));
  HS65_LS_AOI12X2 g2778(.A (n_1), .B (n_81), .C (n_15), .Z (n_109));
  HS65_LS_AOI12X2 g2779(.A (n_2), .B (n_68), .C (n_15), .Z (n_108));
  HS65_LS_AOI12X2 g2780(.A (n_1), .B (n_56), .C (n_15), .Z (n_107));
  HS65_LS_OA222X4 g2781(.A (n_37), .B (n_53), .C (n_38), .D (n_54), .E
       (n_52), .F (n_63), .Z (n_106));
  HS65_LS_OA222X4 g2782(.A (n_30), .B (n_53), .C (n_31), .D (n_54), .E
       (n_52), .F (n_66), .Z (n_105));
  HS65_LS_OA22X9 g2783(.A (n_51), .B (n_66), .C (n_52), .D (n_74), .Z
       (n_104));
  HS65_LS_OA22X9 g2784(.A (n_51), .B (n_63), .C (n_52), .D (n_64), .Z
       (n_103));
  HS65_LS_OA22X9 g2785(.A (n_51), .B (n_69), .C (n_52), .D (n_71), .Z
       (n_102));
  HS65_LS_OA22X9 g2786(.A (n_51), .B (n_73), .C (n_52), .D (n_57), .Z
       (n_101));
  HS65_LS_AOI22X6 g2787(.A (n_2), .B (n_79), .C (SH[2]), .D (n_62), .Z
       (n_100));
  HS65_LS_AOI22X6 g2788(.A (n_1), .B (n_77), .C (SH[2]), .D (n_80), .Z
       (n_99));
  HS65_LS_AOI22X6 g2789(.A (n_2), .B (n_76), .C (SH[2]), .D (n_59), .Z
       (n_98));
  HS65_LS_AOI22X6 g2790(.A (n_1), .B (n_75), .C (SH[2]), .D (n_78), .Z
       (n_97));
  HS65_LS_MUX21I1X6 g2791(.D0 (n_58), .D1 (n_74), .S0 (n_1), .Z (n_96));
  HS65_LS_MUX21I1X6 g2792(.D0 (n_61), .D1 (n_64), .S0 (n_2), .Z (n_95));
  HS65_LS_AOI22X6 g2793(.A (n_2), .B (n_72), .C (SH[2]), .D (n_60), .Z
       (n_94));
  HS65_LS_MUX21I1X6 g2794(.D0 (n_79), .D1 (n_71), .S0 (n_1), .Z (n_93));
  HS65_LS_AOI22X6 g2795(.A (n_2), .B (n_78), .C (SH[2]), .D (n_81), .Z
       (n_92));
  HS65_LS_MUX21I1X6 g2796(.D0 (n_76), .D1 (n_57), .S0 (n_2), .Z (n_91));
  HS65_LS_AOI22X6 g2797(.A (n_2), .B (n_67), .C (SH[2]), .D (n_70), .Z
       (n_90));
  HS65_LS_AOI22X6 g2798(.A (n_1), .B (n_65), .C (SH[2]), .D (n_55), .Z
       (n_89));
  HS65_LS_AOI22X6 g2799(.A (n_2), .B (n_60), .C (SH[2]), .D (n_68), .Z
       (n_88));
  HS65_LS_AOI22X6 g2800(.A (n_1), .B (n_62), .C (SH[2]), .D (n_75), .Z
       (n_87));
  HS65_LS_AOI22X6 g2801(.A (n_2), .B (n_59), .C (SH[2]), .D (n_72), .Z
       (n_86));
  HS65_LS_AOI22X6 g2802(.A (n_2), .B (n_70), .C (SH[2]), .D (n_56), .Z
       (n_85));
  HS65_LS_AOI22X6 g2803(.A (n_1), .B (n_58), .C (SH[2]), .D (n_67), .Z
       (n_84));
  HS65_LS_AOI22X6 g2804(.A (n_1), .B (n_61), .C (SH[2]), .D (n_65), .Z
       (n_83));
  HS65_LS_AOI22X6 g2805(.A (n_2), .B (n_55), .C (SH[2]), .D (n_77), .Z
       (n_82));
  HS65_LS_OAI12X3 g2806(.A (n_49), .B (n_6), .C (n_18), .Z (n_81));
  HS65_LS_OAI12X3 g2807(.A (n_41), .B (SH[1]), .C (n_18), .Z (n_80));
  HS65_LS_OAI22X6 g2808(.A (SH[1]), .B (n_36), .C (n_12), .D (n_19), .Z
       (n_79));
  HS65_LS_OAI22X6 g2809(.A (SH[1]), .B (n_40), .C (n_5), .D (n_24), .Z
       (n_78));
  HS65_LS_OAI22X6 g2810(.A (n_6), .B (n_43), .C (n_5), .D (n_22), .Z
       (n_77));
  HS65_LS_OAI22X6 g2811(.A (SH[1]), .B (n_44), .C (n_12), .D (n_20), .Z
       (n_76));
  HS65_LS_OAI22X6 g2812(.A (n_6), .B (n_21), .C (n_5), .D (n_23), .Z
       (n_75));
  HS65_LS_MUX21X4 g2813(.D0 (n_36), .D1 (n_42), .S0 (n_5), .Z (n_74));
  HS65_LS_MUX21X4 g2814(.D0 (n_45), .D1 (n_38), .S0 (n_5), .Z (n_73));
  HS65_LS_OAI22X6 g2815(.A (SH[1]), .B (n_35), .C (n_5), .D (n_48), .Z
       (n_72));
  HS65_LS_MUX21X4 g2816(.D0 (n_47), .D1 (n_42), .S0 (SH[1]), .Z (n_71));
  HS65_LS_OAI22X6 g2817(.A (n_6), .B (n_23), .C (n_5), .D (n_40), .Z
       (n_70));
  HS65_LS_MUX21X4 g2818(.D0 (n_33), .D1 (n_31), .S0 (n_5), .Z (n_69));
  HS65_LS_OAI22X6 g2819(.A (n_6), .B (n_22), .C (n_5), .D (n_41), .Z
       (n_68));
  HS65_LS_OAI22X6 g2820(.A (n_6), .B (n_39), .C (n_5), .D (n_21), .Z
       (n_67));
  HS65_LS_MUX21X4 g2821(.D0 (n_33), .D1 (n_47), .S0 (n_6), .Z (n_66));
  HS65_LS_OAI22X6 g2822(.A (SH[1]), .B (n_46), .C (n_5), .D (n_35), .Z
       (n_65));
  HS65_LS_MUX21X4 g2823(.D0 (n_32), .D1 (n_44), .S0 (n_6), .Z (n_64));
  HS65_LS_MUX21X4 g2824(.D0 (n_45), .D1 (n_28), .S0 (SH[1]), .Z (n_63));
  HS65_LS_OAI22X6 g2825(.A (n_6), .B (n_27), .C (n_5), .D (n_39), .Z
       (n_62));
  HS65_LS_OAI22X6 g2826(.A (SH[1]), .B (n_20), .C (n_12), .D (n_26), .Z
       (n_61));
  HS65_LS_OAI22X6 g2827(.A (SH[1]), .B (n_25), .C (n_5), .D (n_43), .Z
       (n_60));
  HS65_LS_OAI22X6 g2828(.A (SH[1]), .B (n_26), .C (n_5), .D (n_46), .Z
       (n_59));
  HS65_LS_OAI22X6 g2829(.A (SH[1]), .B (n_19), .C (n_12), .D (n_27), .Z
       (n_58));
  HS65_LS_MUX21X4 g2830(.D0 (n_28), .D1 (n_32), .S0 (n_6), .Z (n_57));
  HS65_LS_OAI22X6 g2831(.A (SH[1]), .B (n_24), .C (n_5), .D (n_49), .Z
       (n_56));
  HS65_LS_OAI22X6 g2832(.A (SH[1]), .B (n_48), .C (n_5), .D (n_25), .Z
       (n_55));
  HS65_LS_NAND2X7 g2833(.A (n_6), .B (n_50), .Z (n_54));
  HS65_LS_NAND2X7 g2834(.A (n_12), .B (n_50), .Z (n_53));
  HS65_LS_NAND2X7 g2835(.A (SH[2]), .B (n_14), .Z (n_52));
  HS65_LS_IVX9 g2836(.A (n_50), .Z (n_51));
  HS65_LS_NOR2X6 g2837(.A (SH[2]), .B (n_0), .Z (n_50));
  HS65_LS_AOI22X6 g2838(.A (n_3), .B (A[29]), .C (n_10), .D (A[30]), .Z
       (n_49));
  HS65_LS_AOI22X6 g2839(.A (n_4), .B (A[22]), .C (n_10), .D (A[23]), .Z
       (n_48));
  HS65_LS_AOI22X6 g2840(.A (n_3), .B (A[9]), .C (n_10), .D (A[10]), .Z
       (n_47));
  HS65_LS_AOI22X6 g2841(.A (n_4), .B (A[18]), .C (n_9), .D (A[19]), .Z
       (n_46));
  HS65_LS_AOI22X6 g2842(.A (n_4), .B (A[6]), .C (n_10), .D (A[7]), .Z
       (n_45));
  HS65_LS_AOI22X6 g2843(.A (n_3), .B (A[12]), .C (n_10), .D (A[13]), .Z
       (n_44));
  HS65_LS_AOI22X6 g2844(.A (n_4), .B (A[26]), .C (n_10), .D (A[27]), .Z
       (n_43));
  HS65_LS_AOI22X6 g2845(.A (n_4), .B (A[11]), .C (n_10), .D (A[12]), .Z
       (n_42));
  HS65_LS_AOI22X6 g2846(.A (n_4), .B (A[30]), .C (n_10), .D (A[31]), .Z
       (n_41));
  HS65_LS_AOI22X6 g2847(.A (n_3), .B (A[25]), .C (n_10), .D (A[26]), .Z
       (n_40));
  HS65_LS_AOI22X6 g2848(.A (n_3), .B (A[19]), .C (n_10), .D (A[20]), .Z
       (n_39));
  HS65_LS_AOI22X6 g2849(.A (n_4), .B (A[4]), .C (SH[0]), .D (A[5]), .Z
       (n_38));
  HS65_LS_AOI22X6 g2850(.A (n_4), .B (A[2]), .C (n_9), .D (A[3]), .Z
       (n_37));
  HS65_LS_AOI22X6 g2851(.A (n_3), .B (A[13]), .C (n_10), .D (A[14]), .Z
       (n_36));
  HS65_LS_AOI22X6 g2852(.A (n_3), .B (A[20]), .C (SH[0]), .D (A[21]),
       .Z (n_35));
  HS65_LS_AOI22X6 g2853(.A (A[1]), .B (n_4), .C (n_9), .D (A[2]), .Z
       (n_34));
  HS65_LS_AOI22X6 g2854(.A (n_4), .B (A[7]), .C (n_9), .D (A[8]), .Z
       (n_33));
  HS65_LS_AOI22X6 g2855(.A (n_4), .B (A[10]), .C (n_10), .D (A[11]), .Z
       (n_32));
  HS65_LS_AOI22X6 g2856(.A (n_4), .B (A[5]), .C (n_9), .D (A[6]), .Z
       (n_31));
  HS65_LS_AOI22X6 g2857(.A (n_4), .B (A[3]), .C (n_10), .D (A[4]), .Z
       (n_30));
  HS65_LS_AOI22X6 g2858(.A (A[0]), .B (n_4), .C (A[1]), .D (n_9), .Z
       (n_29));
  HS65_LS_AOI22X6 g2859(.A (n_3), .B (A[8]), .C (n_10), .D (A[9]), .Z
       (n_28));
  HS65_LS_AOI22X6 g2860(.A (n_3), .B (A[17]), .C (n_10), .D (A[18]), .Z
       (n_27));
  HS65_LS_AOI22X6 g2861(.A (n_3), .B (A[16]), .C (SH[0]), .D (A[17]),
       .Z (n_26));
  HS65_LS_AOI22X6 g2862(.A (n_3), .B (A[24]), .C (SH[0]), .D (A[25]),
       .Z (n_25));
  HS65_LS_AOI22X6 g2863(.A (n_4), .B (A[27]), .C (SH[0]), .D (A[28]),
       .Z (n_24));
  HS65_LS_AOI22X6 g2864(.A (n_4), .B (A[23]), .C (n_10), .D (A[24]), .Z
       (n_23));
  HS65_LS_AOI22X6 g2865(.A (n_3), .B (A[28]), .C (n_10), .D (A[29]), .Z
       (n_22));
  HS65_LS_AOI22X6 g2866(.A (n_4), .B (A[21]), .C (n_10), .D (A[22]), .Z
       (n_21));
  HS65_LS_AOI22X6 g2867(.A (n_4), .B (A[14]), .C (n_9), .D (A[15]), .Z
       (n_20));
  HS65_LS_AOI22X6 g2868(.A (n_4), .B (A[15]), .C (n_9), .D (A[16]), .Z
       (n_19));
  HS65_LS_NAND2X7 g2869(.A (n_6), .B (A[31]), .Z (n_18));
  HS65_LS_NAND2X7 g2870(.A (SH[3]), .B (A[31]), .Z (n_17));
  HS65_LS_NAND2X7 g2871(.A (SH[4]), .B (A[31]), .Z (n_16));
  HS65_LS_AND2X4 g2872(.A (A[31]), .B (SH[2]), .Z (n_15));
  HS65_LS_IVX9 g2873(.A (n_0), .Z (n_14));
  HS65_LS_NAND2X7 g2875(.A (SH[3]), .B (n_11), .Z (n_13));
  HS65_LS_IVX7 g2877(.A (SH[1]), .Z (n_12));
  HS65_LS_IVX9 g2898(.A (SH[4]), .Z (n_11));
  HS65_LS_IVX9 g2899(.A (SH[2]), .Z (n_2));
  HS65_LS_IVX9 g2918(.A (n_4), .Z (n_9));
  HS65_LS_IVX9 g2923(.A (SH[0]), .Z (n_3));
  HS65_LS_IVX9 drc2930(.A (n_5), .Z (n_6));
  HS65_LS_IVX9 drc2931(.A (SH[1]), .Z (n_5));
  HS65_LS_IVX9 drc2936(.A (n_10), .Z (n_4));
  HS65_LS_IVX9 drc2938(.A (n_3), .Z (n_10));
  HS65_LS_IVX9 drc2944(.A (SH[2]), .Z (n_1));
  HS65_LS_NAND2AX7 g2(.A (SH[3]), .B (n_11), .Z (n_0));
endmodule

module shifter(A, B, Op, Outs);
  input [31:0] A;
  input [4:0] B;
  input [1:0] Op;
  output [31:0] Outs;
  wire [31:0] A;
  wire [4:0] B;
  wire [1:0] Op;
  wire [31:0] Outs;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_104, n_105, n_106, n_107, n_108, n_110;
  wire n_111, n_112, n_113, n_114, n_120, n_121, n_124, n_132;
  wire n_134, n_135, n_136, n_145, n_146, n_149, n_150, n_156;
  wire n_159, n_160, n_164, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_184, n_185, n_186, n_190;
  wire n_191, n_192, n_196, n_198, n_202, n_204;
  shift_left_vhdl_unsigned \SHIFT_LEFT_15_28:sll0070 (.A (A), .SH
       ({B[4], n_11, n_190, B[1], n_185}), .Z ({n_103, n_110, n_146,
       n_169, n_173, n_176, n_134, n_168, n_149, n_181, n_21, n_24,
       n_27, n_30, n_33, n_36, n_40, n_75, n_78, n_81, n_85, n_88,
       n_91, n_100, n_98, n_114, n_105, n_111, n_121, n_164, n_18,
       n_93}));
  shift_right_vhdl_unsigned \SHIFT_RIGHT_16_21:srl0075 (.A (A), .SH
       ({B[4:3], n_191, n_8, n_184}), .Z ({n_101, n_106, n_132, n_167,
       n_172, n_175, n_178, n_156, n_182, n_171, n_20, n_23, n_26,
       n_29, n_32, n_35, n_38, n_74, n_77, n_80, n_84, n_87, n_90,
       n_94, n_97, n_102, n_135, n_108, n_113, n_150, n_179, n_82}));
  arith_shift_right_vhdl_unsigned \SHIFT_RIGHT_17_21:sra0080 (.A (A),
       .SH ({n_202, n_196, n_10, n_9, n_185}), .Z ({UNCONNECTED, n_104,
       n_120, n_159, n_170, n_174, n_177, n_145, n_180, n_160, n_19,
       n_22, n_25, n_28, n_31, n_34, n_37, n_41, n_76, n_79, n_83,
       n_86, n_89, n_92, n_96, n_99, n_124, n_107, n_112, n_136, n_166,
       n_39}));
  HS65_LS_BFX9 g7171(.A (B[3]), .Z (n_11));
  HS65_LS_BFX9 g7170(.A (n_191), .Z (n_10));
  HS65_LS_BFX9 g7162(.A (B[1]), .Z (n_9));
  HS65_LS_BFX9 g7163(.A (B[1]), .Z (n_8));
  HS65_LS_AO222X4 g8005(.A (n_4), .B (n_101), .C (n_6), .D (n_103), .E
       (A[31]), .F (n_2), .Z (Outs[31]));
  HS65_LS_AO222X4 g8006(.A (n_146), .B (n_7), .C (n_1), .D (n_120), .E
       (n_5), .F (n_132), .Z (Outs[29]));
  HS65_LS_AO222X4 g8007(.A (n_173), .B (n_7), .C (n_2), .D (n_170), .E
       (n_4), .F (n_172), .Z (Outs[27]));
  HS65_LS_AO222X4 g8008(.A (n_6), .B (n_149), .C (n_2), .D (n_180), .E
       (n_4), .F (n_182), .Z (Outs[23]));
  HS65_LS_AO222X4 g8009(.A (n_6), .B (n_40), .C (n_4), .D (n_38), .E
       (n_2), .F (n_37), .Z (Outs[15]));
  HS65_LS_AO222X4 g8010(.A (n_6), .B (n_75), .C (n_2), .D (n_41), .E
       (n_5), .F (n_74), .Z (Outs[14]));
  HS65_LS_AO222X4 g8011(.A (n_6), .B (n_181), .C (n_2), .D (n_160), .E
       (n_4), .F (n_171), .Z (Outs[22]));
  HS65_LS_AO222X4 g8012(.A (n_6), .B (n_78), .C (n_1), .D (n_76), .E
       (n_5), .F (n_77), .Z (Outs[13]));
  HS65_LS_AO222X4 g8013(.A (n_6), .B (n_81), .C (n_1), .D (n_79), .E
       (n_5), .F (n_80), .Z (Outs[12]));
  HS65_LS_AO222X4 g8014(.A (n_176), .B (n_6), .C (n_2), .D (n_174), .E
       (n_5), .F (n_175), .Z (Outs[26]));
  HS65_LS_AO222X4 g8015(.A (n_6), .B (n_21), .C (n_2), .D (n_19), .E
       (n_4), .F (n_20), .Z (Outs[21]));
  HS65_LS_AO222X4 g8016(.A (n_7), .B (n_85), .C (n_2), .D (n_83), .E
       (n_5), .F (n_84), .Z (Outs[11]));
  HS65_LS_AO222X4 g8017(.A (n_7), .B (n_88), .C (n_2), .D (n_86), .E
       (n_4), .F (n_87), .Z (Outs[10]));
  HS65_LS_AO222X4 g8018(.A (n_6), .B (n_24), .C (n_1), .D (n_22), .E
       (n_4), .F (n_23), .Z (Outs[20]));
  HS65_LS_AO222X4 g8019(.A (n_7), .B (n_91), .C (n_2), .D (n_89), .E
       (n_5), .F (n_90), .Z (Outs[9]));
  HS65_LS_AO222X4 g8020(.A (n_7), .B (n_100), .C (n_1), .D (n_92), .E
       (n_5), .F (n_94), .Z (Outs[8]));
  HS65_LS_AO222X4 g8021(.A (n_110), .B (n_7), .C (n_1), .D (n_104), .E
       (n_106), .F (n_5), .Z (Outs[30]));
  HS65_LS_AO222X4 g8022(.A (n_6), .B (n_134), .C (n_2), .D (n_177), .E
       (n_4), .F (n_178), .Z (Outs[25]));
  HS65_LS_AO222X4 g8023(.A (n_6), .B (n_27), .C (n_1), .D (n_25), .E
       (n_4), .F (n_26), .Z (Outs[19]));
  HS65_LS_AO222X4 g8024(.A (n_7), .B (n_98), .C (n_1), .D (n_96), .E
       (n_5), .F (n_97), .Z (Outs[7]));
  HS65_LS_AO222X4 g8025(.A (n_7), .B (n_114), .C (n_1), .D (n_99), .E
       (n_5), .F (n_102), .Z (Outs[6]));
  HS65_LS_AO222X4 g8026(.A (n_6), .B (n_30), .C (n_1), .D (n_28), .E
       (n_5), .F (n_29), .Z (Outs[18]));
  HS65_LS_AO222X4 g8027(.A (n_7), .B (n_105), .C (n_2), .D (n_124), .E
       (n_5), .F (n_135), .Z (Outs[5]));
  HS65_LS_AO222X4 g8028(.A (n_7), .B (n_111), .C (n_2), .D (n_107), .E
       (n_4), .F (n_108), .Z (Outs[4]));
  HS65_LS_AO222X4 g8029(.A (n_169), .B (n_7), .C (n_2), .D (n_159), .E
       (n_4), .F (n_167), .Z (Outs[28]));
  HS65_LS_AO222X4 g8030(.A (n_6), .B (n_33), .C (n_2), .D (n_31), .E
       (n_5), .F (n_32), .Z (Outs[17]));
  HS65_LS_AO222X4 g8031(.A (n_7), .B (n_121), .C (n_1), .D (n_112), .E
       (n_5), .F (n_113), .Z (Outs[3]));
  HS65_LS_AO222X4 g8032(.A (n_7), .B (n_164), .C (n_2), .D (n_136), .E
       (n_4), .F (n_150), .Z (Outs[2]));
  HS65_LS_AO222X4 g8033(.A (n_6), .B (n_168), .C (n_2), .D (n_145), .E
       (n_4), .F (n_156), .Z (Outs[24]));
  HS65_LS_AO222X4 g8034(.A (n_7), .B (n_18), .C (n_1), .D (n_166), .E
       (n_4), .F (n_179), .Z (Outs[1]));
  HS65_LS_AO222X4 g8035(.A (n_6), .B (n_36), .C (n_1), .D (n_34), .E
       (n_4), .F (n_35), .Z (Outs[16]));
  HS65_LS_AO222X4 g8036(.A (n_7), .B (n_93), .C (n_5), .D (n_82), .E
       (n_1), .F (n_39), .Z (Outs[0]));
  HS65_LS_BFX9 g8038(.A (n_7), .Z (n_6));
  HS65_LS_NOR2X6 g8039(.A (Op[1]), .B (Op[0]), .Z (n_7));
  HS65_LS_NOR2AX3 g8041(.A (Op[1]), .B (Op[0]), .Z (n_5));
  HS65_LS_AND2X4 g8043(.A (Op[1]), .B (Op[0]), .Z (n_2));
  HS65_LS_IVX9 drc8049(.A (n_3), .Z (n_4));
  HS65_LS_IVX9 drc8050(.A (n_5), .Z (n_3));
  HS65_LS_IVX9 drc8056(.A (n_0), .Z (n_1));
  HS65_LS_IVX9 drc8057(.A (n_2), .Z (n_0));
  HS65_LS_IVX9 drc(.A (n_186), .Z (n_184));
  HS65_LS_IVX9 drc8058(.A (n_186), .Z (n_185));
  HS65_LS_IVX9 drc8059(.A (B[0]), .Z (n_186));
  HS65_LS_IVX9 drc8061(.A (n_192), .Z (n_190));
  HS65_LS_IVX9 drc8062(.A (n_192), .Z (n_191));
  HS65_LS_IVX9 drc8063(.A (B[2]), .Z (n_192));
  HS65_LS_IVX9 drc8065(.A (n_198), .Z (n_196));
  HS65_LS_IVX9 drc8067(.A (B[3]), .Z (n_198));
  HS65_LS_IVX9 drc8069(.A (n_204), .Z (n_202));
  HS65_LS_IVX9 drc8071(.A (B[4]), .Z (n_204));
endmodule

module sltu(V, Cout, Sign, Op, Outs);
  input V, Cout, Sign, Op;
  output [31:0] Outs;
  wire V, Cout, Sign, Op;
  wire [31:0] Outs;
  wire n_0, n_1;
  assign Outs[1] = 1'b0;
  assign Outs[2] = 1'b0;
  assign Outs[3] = 1'b0;
  assign Outs[4] = 1'b0;
  assign Outs[5] = 1'b0;
  assign Outs[6] = 1'b0;
  assign Outs[7] = 1'b0;
  assign Outs[8] = 1'b0;
  assign Outs[9] = 1'b0;
  assign Outs[10] = 1'b0;
  assign Outs[11] = 1'b0;
  assign Outs[12] = 1'b0;
  assign Outs[13] = 1'b0;
  assign Outs[14] = 1'b0;
  assign Outs[15] = 1'b0;
  assign Outs[16] = 1'b0;
  assign Outs[17] = 1'b0;
  assign Outs[18] = 1'b0;
  assign Outs[19] = 1'b0;
  assign Outs[20] = 1'b0;
  assign Outs[21] = 1'b0;
  assign Outs[22] = 1'b0;
  assign Outs[23] = 1'b0;
  assign Outs[24] = 1'b0;
  assign Outs[25] = 1'b0;
  assign Outs[26] = 1'b0;
  assign Outs[27] = 1'b0;
  assign Outs[28] = 1'b0;
  assign Outs[29] = 1'b0;
  assign Outs[30] = 1'b0;
  assign Outs[31] = 1'b0;
  HS65_LS_OAI21X6 g574(.A (Op), .B (n_1), .C (n_0), .Z (Outs[0]));
  HS65_LSS_XNOR2X6 g575(.A (Sign), .B (V), .Z (n_1));
  HS65_LS_NAND2AX7 g2(.A (Cout), .B (Op), .Z (n_0));
endmodule

module ALU_RCA(Clk, Reset, A, B, Op, Outs);
  input Clk, Reset;
  input [31:0] A, B;
  input [3:0] Op;
  output [31:0] Outs;
  wire Clk, Reset;
  wire [31:0] A, B;
  wire [3:0] Op;
  wire [31:0] Outs;
  wire [31:0] Areg;
  wire [31:0] addOut;
  wire [31:0] Breg;
  wire [3:0] Opreg;
  wire [31:0] logicOut;
  wire [31:0] shiftOut;
  wire [31:0] sltOut;
  wire Cout, \Opreg[0]_73 , \Opreg[1]_74 , UNCONNECTED0, UNCONNECTED1,
       UNCONNECTED2, UNCONNECTED3, UNCONNECTED4;
  wire UNCONNECTED5, UNCONNECTED6, UNCONNECTED7, UNCONNECTED8,
       UNCONNECTED9, UNCONNECTED10, UNCONNECTED11, UNCONNECTED12;
  wire UNCONNECTED13, UNCONNECTED14, UNCONNECTED15, UNCONNECTED16,
       UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20;
  wire UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24,
       UNCONNECTED25, UNCONNECTED26, UNCONNECTED27, UNCONNECTED28;
  wire UNCONNECTED29, UNCONNECTED30, V, n_0, n_1, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_164, n_165, n_167, n_183, n_192, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_251, n_322, n_323, n_324, n_325, n_327;
  wire n_328, n_329, n_330, n_331, n_332, n_333, n_334, n_335;
  wire n_336, n_337, n_338, n_339, n_340, n_341, n_342, n_343;
  wire n_344, n_345, n_346, n_347, n_356, n_357, n_358, n_359;
  wire n_360, n_361, n_362, n_363, n_364, n_381, n_382, n_383;
  wire n_384;
  RCA au0(.A ({Areg[31:5], n_251, n_322, Areg[2:0]}), .B ({n_347,
       n_334, n_346, n_330, n_345, n_340, n_333, n_329, n_344, n_343,
       n_339, n_336, n_332, n_331, n_224, n_222, n_241, n_240, n_342,
       n_341, n_338, n_337, n_335, n_327, n_359, n_357, n_360, n_361,
       n_362, n_363, n_364, n_328}), .Cin (n_164), .Op (1'b0), .S
       (addOut), .Cout (Cout), .V (V));
  logic_unit lu0(.A ({Areg[31:5], n_251, n_322, Areg[2:1], n_165}), .B
       ({n_245, n_230, n_244, n_226, n_243, n_236, n_229, n_223, n_242,
       n_239, n_235, n_232, n_228, n_227, n_225, n_246, n_248, n_324,
       n_238, n_237, n_234, n_233, n_231, n_221, n_192, n_358, n_356,
       n_183, n_249, Breg[2], n_167, n_323}), .Op ({n_164, Opreg[0]}),
       .Outs (logicOut));
  shifter sft0(.A ({Areg[31:5], n_251, n_322, Areg[2:1], n_165}), .B
       ({n_183, n_249, Breg[2], n_167, n_323}), .Op ({n_164,
       Opreg[0]}), .Outs (shiftOut));
  sltu slt0(.V (V), .Cout (Cout), .Sign (addOut[31]), .Op (Opreg[0]),
       .Outs ({UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, UNCONNECTED3,
       UNCONNECTED4, UNCONNECTED5, UNCONNECTED6, UNCONNECTED7,
       UNCONNECTED8, UNCONNECTED9, UNCONNECTED10, UNCONNECTED11,
       UNCONNECTED12, UNCONNECTED13, UNCONNECTED14, UNCONNECTED15,
       UNCONNECTED16, UNCONNECTED17, UNCONNECTED18, UNCONNECTED19,
       UNCONNECTED20, UNCONNECTED21, UNCONNECTED22, UNCONNECTED23,
       UNCONNECTED24, UNCONNECTED25, UNCONNECTED26, UNCONNECTED27,
       UNCONNECTED28, UNCONNECTED29, UNCONNECTED30, sltOut[0]}));
  HS65_LS_BFX9 g15288(.A (Areg[0]), .Z (n_165));
  HS65_LS_BFX9 g15284(.A (n_247), .Z (n_167));
  HS65_LS_BFX31 g15292(.A (n_325), .Z (n_164));
  HS65_LS_MUX21X4 g15543(.D0 (n_146), .D1 (n_147), .S0 (n_245), .Z
       (n_347));
  HS65_LS_MUX21X4 g15544(.D0 (n_146), .D1 (n_147), .S0 (n_244), .Z
       (n_346));
  HS65_LS_MUX21X4 g15545(.D0 (n_146), .D1 (n_147), .S0 (n_243), .Z
       (n_345));
  HS65_LS_MUX21X4 g15546(.D0 (n_146), .D1 (n_147), .S0 (n_242), .Z
       (n_344));
  HS65_LS_MUX21I1X6 g15547(.D0 (n_248), .D1 (n_248), .S0 (n_145), .Z
       (n_241));
  HS65_LS_MUX21I1X6 g15548(.D0 (n_324), .D1 (n_324), .S0 (n_145), .Z
       (n_240));
  HS65_LS_MUX21X4 g15549(.D0 (n_146), .D1 (n_147), .S0 (n_239), .Z
       (n_343));
  HS65_LS_MUX21X4 g15550(.D0 (n_146), .D1 (n_145), .S0 (n_238), .Z
       (n_342));
  HS65_LS_MUX21X4 g15551(.D0 (n_144), .D1 (n_145), .S0 (n_237), .Z
       (n_341));
  HS65_LS_MUX21X4 g15552(.D0 (n_146), .D1 (n_147), .S0 (n_236), .Z
       (n_340));
  HS65_LS_MUX21X4 g15553(.D0 (n_146), .D1 (n_147), .S0 (n_235), .Z
       (n_339));
  HS65_LS_MUX21X4 g15554(.D0 (n_144), .D1 (n_145), .S0 (n_234), .Z
       (n_338));
  HS65_LS_MUX21X4 g15555(.D0 (n_144), .D1 (n_145), .S0 (n_233), .Z
       (n_337));
  HS65_LS_MUX21X4 g15556(.D0 (n_146), .D1 (n_147), .S0 (n_232), .Z
       (n_336));
  HS65_LS_MUX21X4 g15557(.D0 (n_144), .D1 (n_145), .S0 (n_231), .Z
       (n_335));
  HS65_LS_MUX21X4 g15558(.D0 (n_144), .D1 (n_145), .S0 (n_221), .Z
       (n_327));
  HS65_LS_MUX21X4 g15559(.D0 (n_146), .D1 (n_147), .S0 (n_230), .Z
       (n_334));
  HS65_LS_MUX21X4 g15560(.D0 (n_146), .D1 (n_147), .S0 (n_229), .Z
       (n_333));
  HS65_LS_MUX21X4 g15561(.D0 (n_146), .D1 (n_147), .S0 (n_228), .Z
       (n_332));
  HS65_LS_MUX21I1X6 g15562(.D0 (n_149), .D1 (n_149), .S0 (n_144), .Z
       (n_359));
  HS65_LS_MUX21X4 g15564(.D0 (n_146), .D1 (n_147), .S0 (n_227), .Z
       (n_331));
  HS65_LS_MUX21X4 g15567(.D0 (n_146), .D1 (n_147), .S0 (n_226), .Z
       (n_330));
  HS65_LS_MUX21I1X6 g15568(.D0 (n_145), .D1 (n_145), .S0 (n_225), .Z
       (n_224));
  HS65_LS_MUX21X4 g15571(.D0 (n_146), .D1 (n_147), .S0 (n_223), .Z
       (n_329));
  HS65_LS_MUX21I1X6 g15573(.D0 (n_246), .D1 (n_246), .S0 (n_145), .Z
       (n_222));
  HS65_LS_MUX21X18 g15574(.D0 (n_325), .D1 (n_148), .S0 (n_323), .Z
       (n_328));
  HS65_LS_IVX9 g15583(.A (n_249), .Z (n_150));
  HS65_LS_IVX9 g15584(.A (n_192), .Z (n_149));
  HS65_LS_IVX9 g15587(.A (n_325), .Z (n_148));
  HS65_LS_IVX9 g15619(.A (n_146), .Z (n_147));
  HS65_LS_IVX9 g15620(.A (n_145), .Z (n_146));
  HS65_LS_IVX9 g15637(.A (n_145), .Z (n_144));
  HS65_LS_IVX27 g15640(.A (n_325), .Z (n_145));
  HS65_LS_MUXI21X2 g15696(.D0 (n_145), .D1 (n_144), .S0 (n_358), .Z
       (n_357));
  HS65_LS_DFPQX9 \Areg_reg[0] (.CP (Clk), .D (n_76), .Q (Areg[0]));
  HS65_LSS_DFPQX18 \Areg_reg[10] (.CP (Clk), .D (n_21), .Q (Areg[10]));
  HS65_LSS_DFPQX18 \Areg_reg[11] (.CP (Clk), .D (n_82), .Q (Areg[11]));
  HS65_LSS_DFPQX18 \Areg_reg[12] (.CP (Clk), .D (n_78), .Q (Areg[12]));
  HS65_LSS_DFPQX18 \Areg_reg[13] (.CP (Clk), .D (n_16), .Q (Areg[13]));
  HS65_LSS_DFPQX18 \Areg_reg[14] (.CP (Clk), .D (n_20), .Q (Areg[14]));
  HS65_LSS_DFPQX18 \Areg_reg[15] (.CP (Clk), .D (n_72), .Q (Areg[15]));
  HS65_LSS_DFPQX18 \Areg_reg[16] (.CP (Clk), .D (n_75), .Q (Areg[16]));
  HS65_LSS_DFPQX18 \Areg_reg[17] (.CP (Clk), .D (n_17), .Q (Areg[17]));
  HS65_LSS_DFPQX18 \Areg_reg[18] (.CP (Clk), .D (n_81), .Q (Areg[18]));
  HS65_LS_DFPQX9 \Areg_reg[19] (.CP (Clk), .D (n_15), .Q (Areg[19]));
  HS65_LS_DFPQX9 \Areg_reg[1] (.CP (Clk), .D (n_79), .Q (Areg[1]));
  HS65_LS_DFPQX9 \Areg_reg[20] (.CP (Clk), .D (n_73), .Q (Areg[20]));
  HS65_LS_DFPQX9 \Areg_reg[21] (.CP (Clk), .D (n_19), .Q (Areg[21]));
  HS65_LS_DFPQX9 \Areg_reg[22] (.CP (Clk), .D (n_71), .Q (Areg[22]));
  HS65_LS_DFPQX9 \Areg_reg[23] (.CP (Clk), .D (n_18), .Q (Areg[23]));
  HS65_LS_DFPQX9 \Areg_reg[24] (.CP (Clk), .D (n_77), .Q (Areg[24]));
  HS65_LS_DFPQX9 \Areg_reg[25] (.CP (Clk), .D (n_80), .Q (Areg[25]));
  HS65_LS_DFPQX9 \Areg_reg[26] (.CP (Clk), .D (n_70), .Q (Areg[26]));
  HS65_LS_DFPQX9 \Areg_reg[27] (.CP (Clk), .D (n_68), .Q (Areg[27]));
  HS65_LS_DFPQX9 \Areg_reg[28] (.CP (Clk), .D (n_67), .Q (Areg[28]));
  HS65_LS_DFPQX9 \Areg_reg[29] (.CP (Clk), .D (n_66), .Q (Areg[29]));
  HS65_LS_DFPQX9 \Areg_reg[2] (.CP (Clk), .D (n_65), .Q (Areg[2]));
  HS65_LS_DFPQX9 \Areg_reg[30] (.CP (Clk), .D (n_64), .Q (Areg[30]));
  HS65_LS_DFPQX9 \Areg_reg[31] (.CP (Clk), .D (n_63), .Q (Areg[31]));
  HS65_LS_DFPQX9 \Areg_reg[3] (.CP (Clk), .D (n_62), .Q (n_322));
  HS65_LSS_DFPQX18 \Areg_reg[5] (.CP (Clk), .D (n_59), .Q (Areg[5]));
  HS65_LSS_DFPQX18 \Areg_reg[6] (.CP (Clk), .D (n_57), .Q (Areg[6]));
  HS65_LSS_DFPQX18 \Areg_reg[7] (.CP (Clk), .D (n_58), .Q (Areg[7]));
  HS65_LSS_DFPQX18 \Areg_reg[8] (.CP (Clk), .D (n_56), .Q (Areg[8]));
  HS65_LSS_DFPQX18 \Areg_reg[9] (.CP (Clk), .D (n_54), .Q (Areg[9]));
  HS65_LS_DFPQX9 \Breg_reg[10] (.CP (Clk), .D (n_52), .Q (n_233));
  HS65_LS_DFPQX9 \Breg_reg[11] (.CP (Clk), .D (n_51), .Q (n_234));
  HS65_LS_DFPQX9 \Breg_reg[12] (.CP (Clk), .D (n_49), .Q (n_237));
  HS65_LS_DFPQX9 \Breg_reg[13] (.CP (Clk), .D (n_48), .Q (n_238));
  HS65_LS_DFPQX9 \Breg_reg[14] (.CP (Clk), .D (n_47), .Q (n_324));
  HS65_LS_DFPQX9 \Breg_reg[15] (.CP (Clk), .D (n_46), .Q (n_248));
  HS65_LS_DFPQX9 \Breg_reg[16] (.CP (Clk), .D (n_45), .Q (n_246));
  HS65_LS_DFPQX9 \Breg_reg[17] (.CP (Clk), .D (n_44), .Q (n_225));
  HS65_LS_DFPQX9 \Breg_reg[18] (.CP (Clk), .D (n_43), .Q (n_227));
  HS65_LS_DFPQX9 \Breg_reg[19] (.CP (Clk), .D (n_42), .Q (n_228));
  HS65_LS_DFPQX9 \Breg_reg[20] (.CP (Clk), .D (n_40), .Q (n_232));
  HS65_LS_DFPQX9 \Breg_reg[21] (.CP (Clk), .D (n_39), .Q (n_235));
  HS65_LS_DFPQX9 \Breg_reg[22] (.CP (Clk), .D (n_41), .Q (n_239));
  HS65_LS_DFPQX9 \Breg_reg[23] (.CP (Clk), .D (n_36), .Q (n_242));
  HS65_LS_DFPQX9 \Breg_reg[24] (.CP (Clk), .D (n_37), .Q (n_223));
  HS65_LS_DFPQX9 \Breg_reg[25] (.CP (Clk), .D (n_35), .Q (n_229));
  HS65_LS_DFPQX9 \Breg_reg[26] (.CP (Clk), .D (n_50), .Q (n_236));
  HS65_LS_DFPQX9 \Breg_reg[27] (.CP (Clk), .D (n_34), .Q (n_243));
  HS65_LS_DFPQX9 \Breg_reg[28] (.CP (Clk), .D (n_33), .Q (n_226));
  HS65_LS_DFPQX9 \Breg_reg[29] (.CP (Clk), .D (n_32), .Q (n_244));
  HS65_LS_DFPQX9 \Breg_reg[30] (.CP (Clk), .D (n_31), .Q (n_230));
  HS65_LS_DFPQX9 \Breg_reg[31] (.CP (Clk), .D (n_55), .Q (n_245));
  HS65_LS_DFPQX9 \Breg_reg[3] (.CP (Clk), .D (n_30), .Q (n_249));
  HS65_LS_DFPQX9 \Breg_reg[4] (.CP (Clk), .D (n_69), .Q (n_183));
  HS65_LS_DFPQX9 \Breg_reg[5] (.CP (Clk), .D (n_29), .Q (n_356));
  HS65_LS_DFPQX9 \Breg_reg[6] (.CP (Clk), .D (n_28), .Q (n_358));
  HS65_LS_DFPQX9 \Breg_reg[7] (.CP (Clk), .D (n_27), .Q (n_192));
  HS65_LS_DFPQX9 \Breg_reg[8] (.CP (Clk), .D (n_74), .Q (n_221));
  HS65_LS_DFPQX9 \Breg_reg[9] (.CP (Clk), .D (n_26), .Q (n_231));
  HS65_LSS_DFPQX18 \Opreg_reg[0] (.CP (Clk), .D (n_25), .Q (Opreg[0]));
  HS65_LSS_DFPQNX18 \Opreg_reg[1] (.CP (Clk), .D (n_24), .QN (n_125));
  HS65_LS_DFPQX9 \Opreg_reg[2] (.CP (Clk), .D (n_23), .Q (\Opreg[0]_73
       ));
  HS65_LS_DFPQX9 \Opreg_reg[3] (.CP (Clk), .D (n_22), .Q (\Opreg[1]_74
       ));
  HS65_LS_DFPQX9 \Outs_reg[10] (.CP (Clk), .D (n_110), .Q (Outs[10]));
  HS65_LS_DFPQX9 \Outs_reg[11] (.CP (Clk), .D (n_111), .Q (Outs[11]));
  HS65_LS_DFPQX9 \Outs_reg[12] (.CP (Clk), .D (n_109), .Q (Outs[12]));
  HS65_LS_DFPQX9 \Outs_reg[13] (.CP (Clk), .D (n_108), .Q (Outs[13]));
  HS65_LS_DFPQX9 \Outs_reg[14] (.CP (Clk), .D (n_107), .Q (Outs[14]));
  HS65_LS_DFPQX9 \Outs_reg[15] (.CP (Clk), .D (n_106), .Q (Outs[15]));
  HS65_LS_DFPQX9 \Outs_reg[16] (.CP (Clk), .D (n_105), .Q (Outs[16]));
  HS65_LS_DFPQX9 \Outs_reg[17] (.CP (Clk), .D (n_104), .Q (Outs[17]));
  HS65_LS_DFPQX9 \Outs_reg[18] (.CP (Clk), .D (n_103), .Q (Outs[18]));
  HS65_LS_DFPQX9 \Outs_reg[19] (.CP (Clk), .D (n_102), .Q (Outs[19]));
  HS65_LS_DFPQX9 \Outs_reg[1] (.CP (Clk), .D (n_101), .Q (Outs[1]));
  HS65_LS_DFPQX9 \Outs_reg[20] (.CP (Clk), .D (n_99), .Q (Outs[20]));
  HS65_LS_DFPQX9 \Outs_reg[21] (.CP (Clk), .D (n_100), .Q (Outs[21]));
  HS65_LS_DFPQX9 \Outs_reg[22] (.CP (Clk), .D (n_98), .Q (Outs[22]));
  HS65_LS_DFPQX9 \Outs_reg[23] (.CP (Clk), .D (n_97), .Q (Outs[23]));
  HS65_LS_DFPQX9 \Outs_reg[24] (.CP (Clk), .D (n_96), .Q (Outs[24]));
  HS65_LS_DFPQX9 \Outs_reg[25] (.CP (Clk), .D (n_122), .Q (Outs[25]));
  HS65_LS_DFPQX9 \Outs_reg[26] (.CP (Clk), .D (n_123), .Q (Outs[26]));
  HS65_LS_DFPQX9 \Outs_reg[2] (.CP (Clk), .D (n_121), .Q (Outs[2]));
  HS65_LS_DFPQX9 \Outs_reg[3] (.CP (Clk), .D (n_119), .Q (Outs[3]));
  HS65_LS_DFPQX9 \Outs_reg[4] (.CP (Clk), .D (n_118), .Q (Outs[4]));
  HS65_LS_DFPQX9 \Outs_reg[5] (.CP (Clk), .D (n_117), .Q (Outs[5]));
  HS65_LS_DFPQX9 \Outs_reg[6] (.CP (Clk), .D (n_116), .Q (Outs[6]));
  HS65_LS_DFPQX9 \Outs_reg[7] (.CP (Clk), .D (n_115), .Q (Outs[7]));
  HS65_LS_DFPQX9 \Outs_reg[8] (.CP (Clk), .D (n_114), .Q (Outs[8]));
  HS65_LS_DFPQX9 \Outs_reg[9] (.CP (Clk), .D (n_113), .Q (Outs[9]));
  HS65_LS_NAND2AX7 g16678(.A (n_112), .B (n_87), .Z (n_124));
  HS65_LS_OAI12X3 g16679(.A (n_14), .B (n_6), .C (n_94), .Z (n_123));
  HS65_LS_OAI12X3 g16686(.A (n_12), .B (n_6), .C (n_95), .Z (n_122));
  HS65_LS_AO222X4 g16687(.A (addOut[2]), .B (n_7), .C (n_86), .D
       (shiftOut[2]), .E (n_10), .F (logicOut[2]), .Z (n_121));
  HS65_LS_OAI12X3 g16690(.A (n_6), .B (n_11), .C (n_89), .Z (n_120));
  HS65_LS_AO222X4 g16691(.A (addOut[3]), .B (n_7), .C (n_86), .D
       (shiftOut[3]), .E (n_9), .F (logicOut[3]), .Z (n_119));
  HS65_LS_AO222X4 g16692(.A (addOut[4]), .B (n_7), .C (n_86), .D
       (shiftOut[4]), .E (n_9), .F (logicOut[4]), .Z (n_118));
  HS65_LS_AO222X4 g16693(.A (addOut[5]), .B (n_1), .C (n_86), .D
       (shiftOut[5]), .E (n_9), .F (logicOut[5]), .Z (n_117));
  HS65_LS_AO222X4 g16694(.A (addOut[6]), .B (n_7), .C (n_86), .D
       (shiftOut[6]), .E (n_10), .F (logicOut[6]), .Z (n_116));
  HS65_LS_AO222X4 g16695(.A (addOut[7]), .B (n_7), .C (n_86), .D
       (shiftOut[7]), .E (n_10), .F (logicOut[7]), .Z (n_115));
  HS65_LS_AO222X4 g16696(.A (addOut[8]), .B (n_1), .C (n_86), .D
       (shiftOut[8]), .E (n_9), .F (logicOut[8]), .Z (n_114));
  HS65_LS_AO222X4 g16697(.A (addOut[9]), .B (n_7), .C (n_86), .D
       (shiftOut[9]), .E (n_9), .F (logicOut[9]), .Z (n_113));
  HS65_LS_AO222X4 g16698(.A (addOut[0]), .B (n_1), .C (n_86), .D
       (shiftOut[0]), .E (n_10), .F (logicOut[0]), .Z (n_112));
  HS65_LS_AO222X4 g16699(.A (addOut[11]), .B (n_7), .C (n_86), .D
       (shiftOut[11]), .E (n_9), .F (logicOut[11]), .Z (n_111));
  HS65_LS_AO222X4 g16700(.A (addOut[10]), .B (n_1), .C (n_86), .D
       (shiftOut[10]), .E (n_10), .F (logicOut[10]), .Z (n_110));
  HS65_LS_AO222X4 g16701(.A (logicOut[12]), .B (n_9), .C (n_7), .D
       (addOut[12]), .E (n_85), .F (shiftOut[12]), .Z (n_109));
  HS65_LS_AO222X4 g16702(.A (logicOut[13]), .B (n_9), .C (n_1), .D
       (addOut[13]), .E (n_85), .F (shiftOut[13]), .Z (n_108));
  HS65_LS_AO222X4 g16703(.A (logicOut[14]), .B (n_10), .C (n_1), .D
       (addOut[14]), .E (n_85), .F (shiftOut[14]), .Z (n_107));
  HS65_LS_AO222X4 g16704(.A (logicOut[15]), .B (n_10), .C (n_1), .D
       (addOut[15]), .E (n_85), .F (shiftOut[15]), .Z (n_106));
  HS65_LS_AO222X4 g16705(.A (logicOut[16]), .B (n_9), .C (n_7), .D
       (addOut[16]), .E (n_85), .F (shiftOut[16]), .Z (n_105));
  HS65_LS_AO222X4 g16706(.A (logicOut[17]), .B (n_9), .C (n_7), .D
       (addOut[17]), .E (n_85), .F (shiftOut[17]), .Z (n_104));
  HS65_LS_AO222X4 g16707(.A (logicOut[18]), .B (n_10), .C (n_7), .D
       (addOut[18]), .E (n_85), .F (shiftOut[18]), .Z (n_103));
  HS65_LS_AO222X4 g16708(.A (logicOut[19]), .B (n_10), .C (n_1), .D
       (addOut[19]), .E (n_85), .F (shiftOut[19]), .Z (n_102));
  HS65_LS_AO222X4 g16709(.A (addOut[1]), .B (n_1), .C (n_86), .D
       (shiftOut[1]), .E (n_10), .F (logicOut[1]), .Z (n_101));
  HS65_LS_AO222X4 g16710(.A (logicOut[21]), .B (n_10), .C (n_7), .D
       (addOut[21]), .E (n_85), .F (shiftOut[21]), .Z (n_100));
  HS65_LS_AO222X4 g16711(.A (logicOut[20]), .B (n_10), .C (n_1), .D
       (addOut[20]), .E (n_85), .F (shiftOut[20]), .Z (n_99));
  HS65_LS_AO222X4 g16712(.A (logicOut[22]), .B (n_9), .C (n_1), .D
       (addOut[22]), .E (n_85), .F (shiftOut[22]), .Z (n_98));
  HS65_LS_AO222X4 g16713(.A (n_9), .B (logicOut[23]), .C (n_1), .D
       (addOut[23]), .E (n_85), .F (shiftOut[23]), .Z (n_97));
  HS65_LS_OAI12X3 g16714(.A (n_13), .B (n_6), .C (n_88), .Z (n_96));
  HS65_LS_AOI22X6 g16715(.A (n_10), .B (logicOut[25]), .C (n_85), .D
       (shiftOut[25]), .Z (n_95));
  HS65_LS_AOI22X6 g16716(.A (n_9), .B (logicOut[26]), .C (n_85), .D
       (shiftOut[26]), .Z (n_94));
  HS65_LS_AOI22X6 g16721(.A (n_9), .B (logicOut[31]), .C (n_85), .D
       (shiftOut[31]), .Z (n_89));
  HS65_LS_AOI22X6 g16722(.A (n_10), .B (logicOut[24]), .C (n_85), .D
       (shiftOut[24]), .Z (n_88));
  HS65_LS_NAND2X7 g16723(.A (n_84), .B (sltOut[0]), .Z (n_87));
  HS65_LS_BFX9 g16724(.A (n_86), .Z (n_85));
  HS65_LS_NOR2X6 g16725(.A (n_83), .B (\Opreg[0]_73 ), .Z (n_86));
  HS65_LS_NOR2AX3 g16726(.A (\Opreg[0]_73 ), .B (n_83), .Z (n_84));
  HS65_LS_AND2X4 g16727(.A (n_0), .B (\Opreg[0]_73 ), .Z (n_10));
  HS65_LS_NAND2X7 g16734(.A (Reset), .B (\Opreg[1]_74 ), .Z (n_83));
  HS65_LS_AND2X4 g16805(.A (Reset), .B (A[11]), .Z (n_82));
  HS65_LS_AND2X4 g16806(.A (Reset), .B (A[18]), .Z (n_81));
  HS65_LS_AND2X4 g16807(.A (Reset), .B (A[25]), .Z (n_80));
  HS65_LS_AND2X4 g16808(.A (Reset), .B (A[1]), .Z (n_79));
  HS65_LS_AND2X4 g16809(.A (Reset), .B (A[12]), .Z (n_78));
  HS65_LS_AND2X4 g16810(.A (Reset), .B (A[24]), .Z (n_77));
  HS65_LS_AND2X4 g16811(.A (Reset), .B (A[0]), .Z (n_76));
  HS65_LS_AND2X4 g16812(.A (Reset), .B (A[16]), .Z (n_75));
  HS65_LS_AND2X4 g16813(.A (Reset), .B (B[8]), .Z (n_74));
  HS65_LS_AND2X4 g16814(.A (Reset), .B (A[20]), .Z (n_73));
  HS65_LS_AND2X4 g16815(.A (Reset), .B (A[15]), .Z (n_72));
  HS65_LS_AND2X4 g16816(.A (Reset), .B (A[22]), .Z (n_71));
  HS65_LS_AND2X4 g16817(.A (Reset), .B (A[26]), .Z (n_70));
  HS65_LS_AND2X4 g16818(.A (Reset), .B (B[4]), .Z (n_69));
  HS65_LS_AND2X4 g16819(.A (Reset), .B (A[27]), .Z (n_68));
  HS65_LS_AND2X4 g16820(.A (Reset), .B (A[28]), .Z (n_67));
  HS65_LS_AND2X4 g16821(.A (Reset), .B (A[29]), .Z (n_66));
  HS65_LS_AND2X4 g16822(.A (Reset), .B (A[2]), .Z (n_65));
  HS65_LS_AND2X4 g16823(.A (Reset), .B (A[30]), .Z (n_64));
  HS65_LS_AND2X4 g16824(.A (Reset), .B (A[31]), .Z (n_63));
  HS65_LS_AND2X4 g16825(.A (Reset), .B (A[3]), .Z (n_62));
  HS65_LS_AND2X4 g16826(.A (Reset), .B (A[4]), .Z (n_61));
  HS65_LS_AND2X4 g16827(.A (Reset), .B (B[2]), .Z (n_60));
  HS65_LS_AND2X4 g16828(.A (Reset), .B (A[5]), .Z (n_59));
  HS65_LS_AND2X4 g16829(.A (Reset), .B (A[7]), .Z (n_58));
  HS65_LS_AND2X4 g16830(.A (Reset), .B (A[6]), .Z (n_57));
  HS65_LS_AND2X4 g16831(.A (Reset), .B (A[8]), .Z (n_56));
  HS65_LS_AND2X4 g16832(.A (Reset), .B (B[31]), .Z (n_55));
  HS65_LS_AND2X4 g16833(.A (Reset), .B (A[9]), .Z (n_54));
  HS65_LS_AND2X4 g16834(.A (Reset), .B (B[0]), .Z (n_53));
  HS65_LS_AND2X4 g16835(.A (Reset), .B (B[10]), .Z (n_52));
  HS65_LS_AND2X4 g16836(.A (Reset), .B (B[11]), .Z (n_51));
  HS65_LS_AND2X4 g16837(.A (Reset), .B (B[26]), .Z (n_50));
  HS65_LS_AND2X4 g16838(.A (Reset), .B (B[12]), .Z (n_49));
  HS65_LS_AND2X4 g16839(.A (Reset), .B (B[13]), .Z (n_48));
  HS65_LS_AND2X4 g16840(.A (Reset), .B (B[14]), .Z (n_47));
  HS65_LS_AND2X4 g16841(.A (Reset), .B (B[15]), .Z (n_46));
  HS65_LS_AND2X4 g16842(.A (Reset), .B (B[16]), .Z (n_45));
  HS65_LS_AND2X4 g16843(.A (Reset), .B (B[17]), .Z (n_44));
  HS65_LS_AND2X4 g16844(.A (Reset), .B (B[18]), .Z (n_43));
  HS65_LS_AND2X4 g16845(.A (Reset), .B (B[19]), .Z (n_42));
  HS65_LS_AND2X4 g16846(.A (Reset), .B (B[22]), .Z (n_41));
  HS65_LS_AND2X4 g16847(.A (Reset), .B (B[20]), .Z (n_40));
  HS65_LS_AND2X4 g16848(.A (Reset), .B (B[21]), .Z (n_39));
  HS65_LS_AND2X4 g16849(.A (Reset), .B (B[1]), .Z (n_38));
  HS65_LS_AND2X4 g16850(.A (Reset), .B (B[24]), .Z (n_37));
  HS65_LS_AND2X4 g16851(.A (Reset), .B (B[23]), .Z (n_36));
  HS65_LS_AND2X4 g16852(.A (Reset), .B (B[25]), .Z (n_35));
  HS65_LS_AND2X4 g16853(.A (Reset), .B (B[27]), .Z (n_34));
  HS65_LS_AND2X4 g16854(.A (Reset), .B (B[28]), .Z (n_33));
  HS65_LS_AND2X4 g16855(.A (Reset), .B (B[29]), .Z (n_32));
  HS65_LS_AND2X4 g16856(.A (Reset), .B (B[30]), .Z (n_31));
  HS65_LS_AND2X4 g16857(.A (Reset), .B (B[3]), .Z (n_30));
  HS65_LS_AND2X4 g16858(.A (Reset), .B (B[5]), .Z (n_29));
  HS65_LS_AND2X4 g16859(.A (Reset), .B (B[6]), .Z (n_28));
  HS65_LS_AND2X4 g16860(.A (Reset), .B (B[7]), .Z (n_27));
  HS65_LS_AND2X4 g16861(.A (Reset), .B (B[9]), .Z (n_26));
  HS65_LS_AND2X4 g16862(.A (Reset), .B (Op[0]), .Z (n_25));
  HS65_LS_AND2X4 g16863(.A (Reset), .B (Op[1]), .Z (n_24));
  HS65_LS_AND2X4 g16864(.A (Reset), .B (Op[2]), .Z (n_23));
  HS65_LS_AND2X4 g16865(.A (Reset), .B (Op[3]), .Z (n_22));
  HS65_LS_AND2X4 g16866(.A (Reset), .B (A[10]), .Z (n_21));
  HS65_LS_AND2X4 g16867(.A (Reset), .B (A[14]), .Z (n_20));
  HS65_LS_AND2X4 g16868(.A (Reset), .B (A[21]), .Z (n_19));
  HS65_LS_AND2X4 g16869(.A (Reset), .B (A[23]), .Z (n_18));
  HS65_LS_AND2X4 g16870(.A (Reset), .B (A[17]), .Z (n_17));
  HS65_LS_AND2X4 g16871(.A (Reset), .B (A[13]), .Z (n_16));
  HS65_LS_AND2X4 g16872(.A (Reset), .B (A[19]), .Z (n_15));
  HS65_LS_IVX27 g16878(.A (n_125), .Z (n_325));
  HS65_LS_IVX9 g16879(.A (addOut[26]), .Z (n_14));
  HS65_LS_IVX9 g16884(.A (addOut[24]), .Z (n_13));
  HS65_LS_IVX9 g16885(.A (addOut[25]), .Z (n_12));
  HS65_LS_IVX9 g16886(.A (addOut[31]), .Z (n_11));
  HS65_LS_IVX9 drc16894(.A (n_8), .Z (n_9));
  HS65_LS_IVX9 drc16895(.A (n_10), .Z (n_8));
  HS65_LS_IVX9 drc16901(.A (n_6), .Z (n_7));
  HS65_LS_IVX9 drc16902(.A (n_1), .Z (n_6));
  HS65_LS_NOR2AX3 g16906(.A (n_0), .B (\Opreg[0]_73 ), .Z (n_1));
  HS65_LS_NOR2AX3 g16907(.A (Reset), .B (\Opreg[1]_74 ), .Z (n_0));
  HS65_LS_MUXI21X2 g16908(.D0 (n_145), .D1 (n_144), .S0 (n_356), .Z
       (n_360));
  HS65_LSS_XNOR2X6 g16909(.A (n_145), .B (n_183), .Z (n_361));
  HS65_LSS_XNOR2X6 g16910(.A (n_144), .B (n_150), .Z (n_362));
  HS65_LS_MUX21X4 g16911(.D0 (n_325), .D1 (n_145), .S0 (Breg[2]), .Z
       (n_363));
  HS65_LS_MUX21X18 g16912(.D0 (n_325), .D1 (n_148), .S0 (n_247), .Z
       (n_364));
  HS65_LS_DFPQX9 \Areg_reg[4] (.CP (Clk), .D (n_61), .Q (n_251));
  HS65_LS_DFPQX9 \Outs_reg[0] (.CP (Clk), .D (n_124), .Q (Outs[0]));
  HS65_LS_DFPQX9 \Outs_reg[29] (.CP (Clk), .D (n_383), .Q (Outs[29]));
  HS65_LS_DFPQX9 \Breg_reg[2] (.CP (Clk), .D (n_60), .Q (Breg[2]));
  HS65_LS_DFPQX9 \Breg_reg[0] (.CP (Clk), .D (n_53), .Q (n_323));
  HS65_LS_DFPQX9 \Outs_reg[28] (.CP (Clk), .D (n_382), .Q (Outs[28]));
  HS65_LS_DFPQX9 \Outs_reg[27] (.CP (Clk), .D (n_381), .Q (Outs[27]));
  HS65_LS_DFPQX9 \Breg_reg[1] (.CP (Clk), .D (n_38), .Q (n_247));
  HS65_LS_DFPQX9 \Outs_reg[31] (.CP (Clk), .D (n_120), .Q (Outs[31]));
  HS65_LS_DFPQX9 \Outs_reg[30] (.CP (Clk), .D (n_384), .Q (Outs[30]));
  HS65_LS_AO222X4 g2(.A (n_1), .B (addOut[27]), .C (n_10), .D
       (logicOut[27]), .E (n_86), .F (shiftOut[27]), .Z (n_381));
  HS65_LS_AO222X4 g16933(.A (n_1), .B (addOut[28]), .C (n_9), .D
       (logicOut[28]), .E (n_86), .F (shiftOut[28]), .Z (n_382));
  HS65_LS_AO222X4 g16934(.A (n_1), .B (addOut[29]), .C (n_9), .D
       (logicOut[29]), .E (n_86), .F (shiftOut[29]), .Z (n_383));
  HS65_LS_AO222X4 g16935(.A (n_1), .B (addOut[30]), .C (n_10), .D
       (logicOut[30]), .E (n_86), .F (shiftOut[30]), .Z (n_384));
endmodule

